const {test}=require('node:test');const assert=require('node:assert/strict');const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');const load=require('./load-typescript.cjs')();
const Calendar=load('components/classes/class-calendar.tsx').default;const {emptyFilters}=load('lib/classes/model.ts');
const profile={id:'p',name:'Recreational Gymnastics',active:true,publication_status:'published',visibility:'internal',category_id:'cat',programme_id:'prog'};
const event={key:'c:2026-09-07',date:'2026-09-07',profile,session:{start_time:'16:00',finish_time:'17:00',venue_id:'v'},colour:'#53933b',coverage:'covered',assigned:2,required:2,excludedSlots:0};
const data={profiles:[profile],categories:[{id:'cat',name:'Gymnastics',active:true}],programmes:[{id:'prog',name:'Skills & Progress',active:true}],venues:[{id:'v',name:'Test sports centre'}]};
function render(extra={}){return renderToStaticMarkup(React.createElement(Calendar,{data,events:[event],loading:false,anchor:'2026-09-07',view:'week',filters:emptyFilters,from:'2026-09-07',to:'2026-09-13',onAnchor(){},onView(){},onFilters(){},onOpen(){},...extra}))}
test('calendar toolbar names the date navigation and segmented view control',()=>{const html=render();assert.match(html,/aria-label="Calendar date navigation"/);assert.match(html,/aria-label="Calendar view"/);assert.match(html,/aria-pressed="true">Week/);assert.match(html,/aria-label="Previous date range"/);assert.match(html,/aria-label="Next date range"/)});
test('secondary filters start collapsed and disclose the number of active filters',()=>{const html=render({filters:{...emptyFilters,status:'draft',visibility:'public'}});assert.match(html,/aria-expanded="false"/);assert.match(html,/classesFilterCount">2/);assert.match(html,/id="classes-additional-filters"[^>]*hidden/);assert.match(html,/Clear filters \(2\)/);assert.doesNotMatch(render(),/>Clear filters/)});
test('cards use human-readable lifecycle, visibility and staffing labels',()=>{for(const coverage of ['covered','understaffed','cancelled','unknown']){const html=render({events:[{...event,coverage}]});assert.ok(html.includes(coverage[0].toUpperCase()+coverage.slice(1)));assert.match(html,/>Published</);assert.match(html,/>Internal</);assert.doesNotMatch(html,/>(covered|understaffed|cancelled|unknown|published|internal)</)}const html=render({events:[{...event,profile:{...profile,publication_status:'draft',visibility:'public'}}]});assert.match(html,/>Draft</);assert.match(html,/>Public</)});
test('cards retain time, identity, venue, programme and slot exclusion details',()=>{const html=render({events:[{...event,excludedSlots:1}]});for(const content of ['16:00','17:00','Recreational Gymnastics','Test sports centre','Skills &amp; Progress','1 excluded slot'])assert.ok(html.includes(content),content)});
test('week is an accessible scroll region while day and list have distinct layouts',()=>{assert.match(render(),/Weekly calendar. Scroll horizontally/);assert.match(render({view:'day',to:'2026-09-07'}),/classesCalendar-day/);assert.match(render({view:'list'}),/classesCalendar-list/)});
test('loading and unavailable data remain explicit and disable Draft creation',()=>{assert.match(render({loading:true,data:null}),/Loading your class calendar/);assert.match(render({data:null}),/The calendar is unavailable/);assert.match(render({data:null}),/disabled=""/)});
test('Month is available and renders all dates in its full Monday–Sunday range',()=>{const html=render({view:'month',from:'2026-08-31',to:'2026-10-04'});assert.match(html,/aria-pressed="true">Month/);assert.equal((html.match(/class="classesDay /g)||[]).length,35);assert.match(html,/dateTime="2026-09-30"|datetime="2026-09-30"/)});
test('Week markup uses independent chronological day stacks without artificial profile rows',()=>{const html=render({events:[event,{...event,key:'late',session:{...event.session,start_time:'18:00'}}]});assert.equal((html.match(/class="classesWeekDay"/g)||[]).length,7);assert.equal((html.match(/class="classesWeekRow"/g)||[]).length,0);assert.equal((html.match(/class="classesEvent"/g)||[]).length,2)});
