const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const React=require('react');const ts=require('typescript');const loader=require('./load-typescript.cjs');
const dashboard=fs.readFileSync('app/dashboard/ui.tsx','utf8');
function nodes(e){if(!e||typeof e!=='object')return [];if(Array.isArray(e))return e.flatMap(nodes);return [e,...nodes(e.props?.children)]}
function fixture(){return {creation_version:2,lifecycle_version:3,editing_version:1,profiles:[{id:'correct-profile',name:'Imported class',active:true,publication_status:'published',visibility:'internal',category_id:null,programme_id:null,start_date:null,end_date:null,capacity:12,minimum_age:null,maximum_age:null,session_length_minutes:60,lead_coaches_required:1,assistant_coaches_required:0,minimum_coaches:1,maximum_coaches:1,session_colour:'#123456'}],sessions:[{id:'recurrence',class_profile_id:'correct-profile',active:true,weekday:1,start_time:'16:00',finish_time:'17:00',break_minutes:0,venue_id:'venue'}],slots:[],venues:[{id:'venue',name:'Venue',active:true}],categories:[],programmes:[],coaches:[],activity:[],shifts:[],exclusions:[]}}
function harness(canEdit=true){const data=fixture(),states=[],refs=[],effects=[];let i=0,j=0,k=0,closed=0;const calls=[],saved=[];
 const client={rpc:async(name,args)=>{calls.push({name,args});return {data:name==='classes_command'?{id:'correct-profile',sessions:data.sessions}:data,error:null}}};
 const mock={...React,useState(init){const n=i++;if(!(n in states))states[n]=n===6?data:n===9?false:typeof init==='function'?init():init;return [states[n],v=>states[n]=typeof v==='function'?v(states[n]):v]},useRef(init){return refs[j++]??=( {current:init})},useMemo:f=>f(),useEffect:f=>{effects[k++]=f}};
 const View=loader({react:mock,'./classes.css':{},'@/lib/supabase/client':{createClient:()=>client}})('components/classes/classes-view.tsx').default;
 const props={overlay:true,canEdit,initialProfileId:'correct-profile',onClose:()=>closed++,onSaved:d=>saved.push(d),onOpenInClasses(){}};
 function render(){i=j=k=0;return View(props)}
 render();effects[1]();
 const consoleOf=()=>nodes(render()).find(n=>n.props?.title==='Imported class');
 return {render,consoleOf,calls,saved,effects,closed:()=>closed,edit(){nodes(consoleOf().props.footer).find(n=>n.props?.children==='Edit class').props.onClick()}};
}
test('Master click sets the correct shared overlay profile without navigating or resetting timetable state',()=>{
 const source=dashboard.slice(dashboard.indexOf('  function openEditClass('),dashboard.indexOf('  function refreshMasterClassData('));
 assert.doesNotMatch(source,/setTab|setMasterTimetableOpen|setMonth|setScheduleFilter|setAdminScheduleDate|setMasterTimetableDay|history|router/);
 let selected;const trigger={};const restore=()=>{};const js=ts.transpile(source,{target:ts.ScriptTarget.ES2022});
 const open=new Function('setMasterClassConsole','captureClassReturnContext',js+';return openEditClass')(v=>selected=v,t=>{assert.equal(t,trigger);return restore});open({class_profile_id:'profile-42'},trigger);assert.deepEqual(selected,{profileId:'profile-42',restore});
 assert.match(dashboard,/masterClassConsole&&<MasterClassOverlay profileId=\{masterClassConsole.profileId\} canEdit=\{isAdmin\}/);
});
test('overlay loads the full correct profile into the Library editor; authorised users can enter Edit',()=>{const h=harness();assert.ok(h.consoleOf());assert.equal(nodes(h.render()).find(n=>n.type==='fieldset').props.disabled,true);assert.doesNotMatch(JSON.stringify(h.render()),/Classes sections/);h.edit();assert.equal(nodes(h.render()).find(n=>n.type==='fieldset').props.disabled,false);assert.ok(nodes(h.consoleOf().props.footer).find(n=>n.props?.children==='Save changes'))});
test('view-only permission hides Edit class and blocks a crafted submission',()=>{const h=harness(false);assert.ok(!nodes(h.consoleOf().props.footer).some(n=>n.props?.children==='Edit class'));nodes(h.render()).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});assert.equal(h.calls.length,0);assert.equal(nodes(h.render()).find(n=>n.type==='fieldset').props.disabled,true)});
test('overlay save uses classes_command, refreshes class data and retains Edit/tab context with temporary feedback',async()=>{const h=harness();h.edit();const schedule=nodes(h.render()).find(n=>n.props?.role==='tab'&&n.props.children==='Schedule');schedule.props.onClick();nodes(h.render()).find(n=>n.type==='form').props.onSubmit({preventDefault(){}});await new Promise(r=>setImmediate(r));assert.deepEqual(h.calls.map(c=>c.name),['classes_command','classes_calendar_data']);assert.equal(h.calls[0].args.p_action,'save');assert.equal(h.calls[0].args.p_data.sessions,null);assert.equal(h.saved.length,1);h.render();h.effects[1]();assert.equal(nodes(h.render()).find(n=>n.type==='fieldset').props.disabled,false);assert.ok(nodes(h.render()).find(n=>n.props?.role==='tab'&&n.props.children==='Schedule').props['aria-selected']);assert.ok(nodes(h.render()).some(n=>n.props?.role==='status'&&n.props.children.includes('Class saved')));
 const previous=global.window;let expire;global.window={setTimeout(f,ms){assert.equal(ms,4500);expire=f;return 1},clearTimeout(){}};try{h.effects[2]();expire();assert.ok(!nodes(h.render()).some(n=>n.props?.role==='status'&&n.props.children.includes('Class saved')))}finally{global.window=previous}
});
test('close signals the overlay owner without navigation; unmount restores focus and all scroll ancestors',async()=>{const h=harness();nodes(h.consoleOf().props.footer).find(n=>n.props?.children==='Back to Master Timetable').props.onClick();assert.equal(h.closed(),1);
 const previous=global.window;const scrolls=[],focus=[];global.window={scrollX:12,scrollY:600,scrollTo:(...xy)=>scrolls.push(xy)};
 try{const parent={scrollTop:240,scrollLeft:40,parentElement:null},trigger={parentElement:parent,isConnected:true,focus:o=>focus.push(o)};const restore=loader()('lib/classes/console-context.ts').captureClassReturnContext(trigger);parent.scrollTop=0;parent.scrollLeft=0;let cleanup;const Overlay=loader({react:{...React,useEffect:f=>cleanup=f()},'./classes-view':{default:()=>null}})('components/classes/master-class-overlay.tsx').default;Overlay({profileId:'p',canEdit:true,restore,onClose(){},onSaved(){},onOpenInClasses(){}});cleanup();await Promise.resolve();assert.equal(parent.scrollTop,240);assert.equal(parent.scrollLeft,40);assert.deepEqual(scrolls,[[12,600]]);assert.deepEqual(focus,[{preventScroll:true},{preventScroll:true}])}finally{global.window=previous}
});
test('Master refresh changes only class templates/slots, retains eligibility and never writes dated data',()=>{const refresh=dashboard.slice(dashboard.indexOf('  function refreshMasterClassData('),dashboard.indexOf('\n  }',dashboard.indexOf('  function refreshMasterClassData('))+4);assert.match(refresh,/setClasses/);assert.match(refresh,/setClassSlots/);assert.doesNotMatch(refresh,/setScheduledShifts|setMonth|setScheduleFilter|setTab|\.rpc|\.from|\.update|\.insert|\.delete/);assert.equal((dashboard.match(/const masterTimetableClasses=classes.filter\(c=>masterClassEligible/g)||[]).length,2);const view=fs.readFileSync('components/classes/classes-view.tsx','utf8');assert.doesNotMatch(view,/client\.from\(|generate_schedule_month|sync_class_schedule|loadSchedule\(/);assert.match(view,/disabled=\{published\}/);assert.match(view,/Change from date/);const css=fs.readFileSync('components/classes/classes.css','utf8');assert.match(css,/minmax\(0,1fr\)/);assert.match(css,/100dvh/);assert.match(css,/overflow-y:auto/)});
