const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const crypto=require('node:crypto');const React=require('react');const loader=require('./load-typescript.cjs');
function fixture(){return {creation_version:2,lifecycle_version:3,editing_version:1,profiles:[{id:'imported',name:'Imported Kirklees class',active:true,publication_status:'published',visibility:'internal',category_id:null,programme_id:null,start_date:null,end_date:null,capacity:12,minimum_age:null,maximum_age:null,session_length_minutes:60,lead_coaches_required:1,assistant_coaches_required:0,minimum_coaches:1,maximum_coaches:1,session_colour:'#123456'}],sessions:[{id:'recurrence',class_profile_id:'imported',active:true,weekday:1,start_time:'16:00',finish_time:'17:15',break_minutes:0,venue_id:'venue'}],slots:[{id:'position',class_id:'recurrence',slot_number:1,active:true,default_profile_id:null,payment_type:'standard'}],venues:[{id:'venue',name:'Venue',active:true}],coaches:[{id:'coach',full_name:'Coach'}],categories:[],programmes:[],qualifications:[],activity:[],shifts:[{id:'dated',profile_id:'existing'}],exclusions:[]}}
function nodes(element){if(element==null||typeof element!=='object')return [];if(Array.isArray(element))return element.flatMap(nodes);return [element,...nodes(element.props?.children)]}
function button(tree,label){const b=nodes(tree).find(n=>n.type==='button'&&n.props.children===label);assert.ok(b,label);return b}
function harness(data=fixture()){
 const states=[],refs=[];let index=0,refIndex=0;const calls=[];
 const mockReact={...React,useState(initial){const i=index++;if(!(i in states))states[i]=i===6?data:i===9?false:typeof initial==='function'?initial():initial;return [states[i],value=>{states[i]=typeof value==='function'?value(states[i]):value}]},useRef(initial){const i=refIndex++;return refs[i]??=( {current:initial})},useMemo:f=>f(),useEffect(){}};
 const client={rpc:async(name,args)=>{calls.push({name,args});return {data:{id:'imported',sessions:data.sessions.map(s=>({...s,staffing:[]}))},error:null}}};
 const View=loader({react:mockReact,'./classes.css':{},'@/lib/supabase/client':{createClient:()=>client}})('components/classes/classes-view.tsx').default;
 function render(){index=0;refIndex=0;return View({})}
 function open(mode){button(render(),'Class Library').props.onClick();const library=nodes(render()).find(n=>n.props?.onLifecycle&&n.props?.onOpen);const Library=loader({react:{...React,useState:x=>[x,()=>{}]}})('components/classes/class-library.tsx').default;button(Library(library.props),mode==='edit'?'Edit':'Open class').props.onClick();return render()}
 return {render,open,calls,data};
}
function form(tree){return nodes(tree).find(n=>n.type==='form')}
function input(tree,label){const l=nodes(tree).find(n=>n.type==='label'&&Array.isArray(n.props.children)&&n.props.children[0]===label);assert.ok(l,label);return nodes(l).find(n=>['input','select','textarea'].includes(n.type))}
function tab(h,label){const t=nodes(h.render()).find(n=>n.props?.role==='tab'&&n.props.children===label);t.props.onClick();return h.render()}
test('Library Edit on imported Published record uses editable form and persistent Save changes / Cancel',()=>{const h=harness(),tree=h.open('edit');assert.equal(h.data.profiles[0].creation_version,undefined);assert.equal(form(tree).props.children.props.disabled,false);assert.equal(input(tree,'Class name').props.disabled,undefined);const console=nodes(tree).find(n=>n.props?.footer);assert.equal(button(console.props.footer,'Save changes').props.form,form(tree).props.id);assert.ok(button(console.props.footer,'Cancel'));assert.equal(input(tree,'Class name').props.value,'Imported Kirklees class')});
test('Library View stays read-only and cannot submit even a crafted form event',()=>{const h=harness(),tree=h.open('view');assert.equal(form(tree).props.children.props.disabled,true);assert.ok(nodes(nodes(tree).find(n=>n.props?.footer).props.footer).some(n=>n.props?.children==='Edit class'));form(tree).props.onSubmit({preventDefault(){}});assert.equal(h.calls.length,0)});
test('timetable occurrence always opens View after an earlier Edit',()=>{const h=harness();h.open('edit');button(h.render(),'Timetable').props.onClick();const calendar=nodes(h.render()).find(n=>n.props?.onAnchor&&n.props?.onOpen);calendar.props.onOpen(h.data.profiles[0]);assert.equal(form(h.render()).props.children.props.disabled,true)});
test('published protected inputs stay disabled while notes/default coaches/payment remain editable',()=>{const h=harness();h.open('edit');let tree=tab(h,'Schedule');for(const name of ['Start date','End date (optional)','Default session duration (minutes)','Day','Start time','Venue','Break (minutes)'])assert.equal(input(tree,name).props.disabled,true,name);assert.equal(input(tree,'Recurrence notes').props.disabled,undefined);assert.ok(button(tree,'Change from date'));tree=tab(h,'Staffing');for(const name of ['Default coach','Payment preference'])assert.equal(input(tree,name).props.disabled,false,name)});
test('safe field edits submit through classes_command and leave dated fixture records unchanged',async()=>{const h=harness(),before=JSON.stringify(h.data.shifts);let tree=h.open('edit');input(tree,'Class name').props.onChange({target:{value:'Renamed class'}});tree=tab(h,'Schedule');input(tree,'Recurrence notes').props.onChange({target:{value:'Bring equipment'}});tree=tab(h,'Staffing');input(tree,'Default coach').props.onChange({target:{value:'coach'}});input(h.render(),'Payment preference').props.onChange({target:{value:'volunteer'}});form(h.render()).props.onSubmit({preventDefault(){}});await new Promise(r=>setImmediate(r));assert.equal(h.calls.length,1);const {name,args}=h.calls[0];assert.equal(name,'classes_command');assert.equal(args.p_action,'save');assert.equal(args.p_profile_id,'imported');assert.equal(args.p_data.sessions,null);assert.equal(args.p_data.profile.name,'Renamed class');assert.deepEqual(args.p_data.profile.session_notes,[{id:'recurrence',notes:'Bring equipment'}]);assert.deepEqual(args.p_data.profile.session_defaults,[{id:'recurrence',staffing:[{slot_number:1,default_profile_id:'coach',payment_type:'volunteer'}]}]);assert.ok(!('club_id' in args.p_data.profile));assert.equal(JSON.stringify(h.data.shifts),before)});
test('old deployment does not silently discard changed published staffing defaults',()=>{const d=fixture();delete d.editing_version;const h=harness(d);h.open('edit');input(tab(h,'Staffing'),'Default coach').props.onChange({target:{value:'coach'}});form(h.render()).props.onSubmit({preventDefault(){}});assert.equal(h.calls.length,0);assert.ok(nodes(h.render()).some(n=>n.props?.role==='alert'&&n.props.children.includes('editor upgrade')))});
const sql=fs.readFileSync('supabase/v1_7_3_classes_editor.sql','utf8');const old=fs.readFileSync('supabase/v1_7_2_classes_lifecycle.sql','utf8');
function body(source,name){return source.match(new RegExp('create (?:or replace )?function public\\.'+name+'\\(.*?(\\$\\$|\\$function\\$)(.*?)\\1\\s*;','s'))[2]}
test('SQL contract rejects crafted protected recurrence payloads and preserves tenant/owner authorization',()=>{const save=body(sql,'classes_save_profile');assert.match(save,/p.publication_status='published' and p_sessions is not null/);assert.match(save,/duration<>p.session_length_minutes/);for(const key of ['start_date','end_date'])assert.ok(save.includes("nullif(p_data->>'"+key+"','')::date is distinct from p."+key));assert.match(save,/jsonb_object_keys\(s\) k where k not in \('id','notes'\)/);assert.match(save,/jsonb_object_keys\(s\) k where k not in \('id','staffing'\)/);assert.match(save,/jsonb_object_keys\(slot\) k where k not in \('slot_number','default_profile_id','payment_type'\)/);assert.match(save,/id=rid and club_id=cid for update/);assert.match(save,/class_profile_id=rid and club_id=cid and active/);assert.match(save,/not public.is_club_admin\(cid\)/);assert.match(fs.readFileSync('supabase/v1_5_platform_admin.sql','utf8'),/p.club_id=p_club and p.role in \('club_owner','org_admin'\)/)});
test('SQL write targets exclude dated tables throughout save and its propagation path; migration only replaces functions',()=>{for(const [source,name] of [[sql,'classes_save_profile'],[old,'classes_command'],[old,'propagate_class_profile_to_sessions'],[old,'apply_class_profile_to_session']])assert.doesNotMatch(body(source,name),/(?:insert into|update|delete from) public\.(?:scheduled_shifts|shifts|timesheets|invoices|schedule_occurrence_exclusions)\b|(?:perform|select) public\.(?:generate_schedule_month|sync_class_schedule)/i);const outside=sql.replace(/create (?:or replace )?function .*?end \$\$;/gs,'');assert.doesNotMatch(outside,/\b(?:insert into|update public|delete from|alter table)\b/i);assert.match(sql,/Reviewed function drift/);assert.match(sql,/revoke all on function public.classes_save_profile\(jsonb,jsonb\) from public,anon,authenticated,service_role/)});
test('forward migration fingerprints and read-only verifier match the reviewed source',()=>{const verify=fs.readFileSync('supabase/verify_v1_7_3_classes_editor.sql','utf8');for(const name of ['classes_save_profile','classes_calendar_data'])assert.ok(verify.includes(crypto.createHash('md5').update(body(sql,name)).digest('hex')));for(const name of ['classes_save_profile','classes_calendar_data','classes_command','propagate_class_profile_to_sessions','apply_class_profile_to_session'])assert.ok(sql.includes(crypto.createHash('md5').update(body(old,name)).digest('hex')),name);assert.doesNotMatch(verify,/^\s*(insert|update|delete|alter|drop|create)\b/im)});
test('metadata propagation preserves imported recurrence times, including mismatched legacy duration',()=>{const propagation=body(old,'propagate_class_profile_to_sessions');assert.doesNotMatch(propagation,/start_time|finish_time|duration_minutes|break_minutes|venue_id/);const published=body(sql,'classes_save_profile').split("if p.publication_status='published' then")[1].split('for sid in select')[0];assert.match(published,/update public.classes set notes=/);assert.doesNotMatch(published,/set (?:start_time|finish_time|duration_minutes|break_minutes|venue_id)/);const trigger=fs.readFileSync('supabase/v1_2_final_kirklees_polish.sql','utf8');assert.match(trigger,/create trigger apply_class_profile_to_session before insert or update of class_profile_id,start_time\s+on public.classes/)});

test('Library and calendar View expose Edit immediately and closing preserves the section and filters',()=>{
 for(const section of ['Class Library','Timetable']){
  const h=harness();button(h.render(),section).props.onClick();
  if(section==='Class Library')h.open('view');else nodes(h.render()).find(n=>n.props?.onAnchor&&n.props?.onOpen).props.onOpen(h.data.profiles[0]);
  const console=nodes(h.render()).find(n=>n.props?.footer);button(console.props.footer,'Edit class').props.onClick();assert.equal(form(h.render()).props.children.props.disabled,false);
  const current=nodes(h.render()).find(n=>n.props?.footer);button(current.props.footer,'Cancel').props.onClick();assert.equal(form(h.render()),undefined);assert.equal(button(h.render(),section).props['aria-pressed'],true);
 }
});
test('calendar date, view and filters survive viewing/editing and closing a class',()=>{
 const h=harness();button(h.render(),'Timetable').props.onClick();const calendar=()=>nodes(h.render()).find(n=>n.props?.onAnchor&&n.props?.onOpen);
 calendar().props.onAnchor('2026-09-15');calendar().props.onView('day');const filters={...calendar().props.filters,venue:'venue',status:'published'};calendar().props.onFilters(filters);
 calendar().props.onOpen(h.data.profiles[0]);button(nodes(h.render()).find(n=>n.props?.footer).props.footer,'Edit class').props.onClick();button(nodes(h.render()).find(n=>n.props?.footer).props.footer,'Cancel').props.onClick();
 assert.equal(calendar().props.anchor,'2026-09-15');assert.equal(calendar().props.view,'day');assert.deepEqual(calendar().props.filters,filters);
});
