const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const crypto=require('node:crypto');const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');const loader=require('./load-typescript.cjs');const load=loader();
const lifecycle=load('lib/classes/lifecycle.ts'),model=load('lib/classes/model.ts');
const sql=fs.readFileSync('supabase/v1_7_2_classes_lifecycle.sql','utf8');
function body(name){const m=sql.match(new RegExp('create (?:or replace )?function public\\.'+name+'\\(.*?(\\$\\$|\\$function\\$)(.*?)\\1\\s*;','si'));assert.ok(m,name);return m[2]}
const command=body('classes_command');
function fixture(){return {lifecycle_version:3,creation_version:2,profiles:[{id:'p',name:'Example',active:true,publication_status:'published',visibility:'internal',category_id:null,programme_id:null,capacity:12,minimum_age:4,maximum_age:10,session_length_minutes:60,lead_coaches_required:1,assistant_coaches_required:1,minimum_coaches:1,maximum_coaches:2,start_date:null,end_date:null,session_colour:'#123456'}],sessions:[{id:'c',class_profile_id:'p',active:true,weekday:1,start_time:'16:00',finish_time:'17:00',break_minutes:0,venue_id:'v'}],venues:[{id:'v',name:'Synthetic venue',active:true}],categories:[],programmes:[],slots:[],shifts:[],exclusions:[],activity:[]}}
test('Timetable is the default and the three management sections are explicit',()=>{const View=loader({'./classes.css':{},'@/lib/supabase/client':{createClient:()=>({})}})('components/classes/classes-view.tsx').default;const html=renderToStaticMarkup(React.createElement(View));assert.match(html,/aria-pressed="true">Timetable/);for(const label of lifecycle.classSections)assert.ok(html.includes(label.replace('&','&amp;')));assert.doesNotMatch(html,/Categories &amp; Programmes/)});
test('Library displays management details and lifecycle actions for imported classes',()=>{const Library=load('components/classes/class-library.tsx').default;const html=renderToStaticMarkup(React.createElement(Library,{data:fixture(),loading:false,onOpen(){},onLifecycle(){}}));for(const value of ['Example','Published','Internal','Weekly sessions','Synthetic venue','Capacity 12','Ages 4','1 lead','Change from date','End class','Archive','Edit'])assert.ok(html.includes(value),value)});
test('active Published profile AND recurrence are required; missing or archived profile fails closed',()=>{const d=fixture(),p=d.profiles[0],s=d.sessions[0];assert.equal(lifecycle.recurrenceEligible(p,s,'2026-09-07'),true);for(const profile of [undefined,{...p,active:false},{...p,publication_status:'draft'}])assert.equal(lifecycle.recurrenceEligible(profile,s,'2026-09-07'),false);assert.equal(lifecycle.recurrenceEligible(p,{...s,active:false},'2026-09-07'),false)});
test('Master Timetable uses actual weekday date inside selected week and excludes inactive profiles',()=>{const row={...fixture().profiles[0],...fixture().sessions[0],profile_active:true};assert.equal(lifecycle.masterClassEligible(row,'2026-09-09'),true);assert.equal(lifecycle.masterClassEligible({...row,end_date:'2026-09-06'},'2026-09-09'),false);assert.equal(lifecycle.masterClassEligible({...row,end_date:'2026-09-07'},'2026-09-09'),true);for(const override of [{active:false},{profile_active:false},{publication_status:'draft'},{profile_active:undefined}])assert.equal(lifecycle.masterClassEligible({...row,...override},'2026-09-09'),false)});
test('Ended state and generation use inclusive final dates',()=>{const p={...fixture().profiles[0],end_date:'2026-09-07'},s=fixture().sessions[0];assert.equal(lifecycle.classState(p,'2026-09-07'),'published');assert.equal(lifecycle.classState(p,'2026-09-08'),'ended');assert.equal(lifecycle.recurrenceEligible(p,s,'2026-09-07'),true);assert.equal(lifecycle.recurrenceEligible(p,s,'2026-09-08'),false);assert.match(body('generate_schedule_month'),/d<=p.end_date/);assert.match(command,/end_date=final_date/)});
test('version boundary selects old recurrence before the change and replacement after it',()=>{const d=fixture();d.sessions[0].effective_to='2026-09-13';d.sessions.push({...d.sessions[0],id:'future',start_time:'18:00',finish_time:'19:30',effective_from:'2026-09-14',effective_to:null});const events=model.expandCalendar(d,'2026-09-07','2026-09-21');assert.deepEqual(events.map(e=>[e.date,e.session.id]),[['2026-09-07','c'],['2026-09-14','future'],['2026-09-21','future']])});
test('archive snapshots active children; restore uses only captured IDs and refuses unsafe legacy restore',()=>{const archive=command.slice(command.indexOf("p_action='archive'"),command.indexOf("p_action='delete'"));assert.match(archive,/archive_state=snapshot/);assert.match(archive,/update public.classes set active=false/);assert.match(archive,/update public.class_staffing_slots set active=false/);assert.match(archive,/jsonb_array_elements_text\(p.archive_state->'sessions'\)/);assert.match(archive,/jsonb_array_elements_text\(p.archive_state->'slots'\)/);assert.match(archive,/No safe archive snapshot exists/);assert.match(body('set_class_profile_active'),/public.classes_command/);assert.doesNotMatch(archive,/delete from|scheduled_shifts/)});
test('unused Draft deletion rechecks dependencies under locks with exact-name confirmation and preserves audit',()=>{const deletion=command.slice(command.indexOf("p_action='delete'"),command.indexOf("p_action='change'"));assert.match(deletion,/p.publication_status<>'draft'/);assert.match(deletion,/confirmation' is distinct from p.name/);assert.match(deletion,/classes_dependencies\(p.id,true\)/);assert.ok(deletion.indexOf('classes_dependencies')<deletion.indexOf('delete from'));assert.match(deletion,/'activity'.*jsonb_agg/s);for(const table of ['class_activity','class_staffing_slots','classes','class_profiles'])assert.match(deletion,new RegExp('delete from public.'+table));assert.match(command,/insert into public.class_lifecycle_audit/);assert.doesNotMatch(sql,/references [^;]+on delete cascade/i)});
test('dependency discovery protects scheduled/actual/confirmed/payroll/exclusion/attendance/enrolment and activity references',()=>{const deps=body('classes_dependencies');assert.match(deps,/pg_constraint fk/);assert.match(deps,/unnest\(fk.conkey,fk.confkey\)/);assert.match(deps,/'class_profile_id','class_id','staffing_slot_id'/);assert.match(deps,/'public.class_activity'::regclass/);assert.match(deps,/lock table %I.%I in share row exclusive mode/);assert.match(deps,/count\(\*\).*%I=any\(\$1\)/);for(const table of ['scheduled_shifts','shifts','timesheets','invoices','schedule_occurrence_exclusions','coaching_assignment_history','enrolments','attendance'])assert.doesNotMatch(deps,new RegExp("table_name (?:not )?in \\([^)]*'"+table+"'"));assert.match(command,/Protected dependencies:.*End or Archive/)});
test('published metadata can save despite imported duration mismatch and propagation never retimes recurrences',()=>{const save=body('classes_save_profile'),prop=body('propagate_class_profile_to_sessions');assert.doesNotMatch(save,/Recurring durations need Master Timetable review/);assert.doesNotMatch(prop,/finish_time|start_time|break_minutes|venue_id/);assert.match(save,/set notes=s->>'notes'/);assert.match(save,/p.publication_status='published' and p_sessions is not null/);assert.match(save,/Published timing and date changes require/);const p={...fixture().profiles[0],end_date:'2026-09-30'};assert.equal(load('lib/classes/draft.ts').validateDraft(p,fixture().sessions),'')});
test('effective-date command rejects generated history and future references before closing old versions',()=>{const change=command.slice(command.indexOf("p_action='change'"));for(const table of ['scheduled_shifts','schedule_occurrence_exclusions','coaching_assignment_history'])assert.ok(change.includes('public.'+table));assert.match(change,/shift_date>=cutoff/);assert.match(change,/cutoff<=actor_today/);assert.match(change,/effective_from>=cutoff/);assert.match(change,/Additional operational references require/);assert.ok(change.indexOf('Generated work or occurrence history')<change.indexOf('update public.classes'));assert.match(change,/cutoff-1/);assert.match(change,/insert into public.classes/);assert.match(change,/old.class_id=old_session.id/)});
test('all new actions preserve existing generated/actual/payroll data and do not auto-generate',()=>{for(const name of ['classes_command','classes_save_profile','classes_publish','propagate_class_profile_to_sessions'])assert.doesNotMatch(body(name),/(?:insert into|update|delete from) public\.(?:scheduled_shifts|shifts|timesheets|invoices|schedule_occurrence_exclusions)\b|perform public\.(?:generate_schedule_month|sync_class_schedule)/i);assert.match(sql,/n is distinct from b.n or h is distinct from b.h/);assert.match(sql,/Operational baseline missing/)});
test('server insertion gate serializes with lifecycle and covers every copy/generation insertion path',()=>{const gate=body('classes_phase1_shift_gate');for(const token of ['for share','not p.active',"p.publication_status<>'published'",'not c.active','not slot.active','new.shift_date>p.end_date','new.shift_date<c.effective_from','new.shift_date>c.effective_to','p.club_id<>new.club_id','slot.class_id<>c.id'])assert.ok(gate.includes(token),token);assert.match(sql,/trg_skip_excluded_scheduled_occurrence/);assert.match(body('generate_schedule_month'),/p.active and p.publication_status='published'/)});
test('cross-club, coach and anonymous mutations fail closed before touching the aggregate',()=>{assert.ok(command.indexOf('not public.is_club_admin(cid)')<command.indexOf('pg_advisory_xact_lock'));assert.match(command,/id=p_profile_id and club_id=cid for update/);assert.match(command,/Replacement source outside class/);assert.match(sql,/revoke all on function public.classes_command\(text,uuid,jsonb,uuid\) from public,anon,authenticated/);assert.match(sql,/revoke insert,update,delete,truncate on public.class_profiles,public.classes,public.class_staffing_slots from public,authenticated,anon/)});
test('server receipts make repeats idempotent and reject reused tokens with different payloads',()=>{assert.match(command,/pg_advisory_xact_lock/);assert.match(command,/receipt.payload_hash<>digest or receipt.actor_id<>auth.uid\(\)/);assert.ok(command.indexOf('return receipt.result')<command.indexOf('if p_profile_id is not null'));assert.match(sql,/unique\(club_id,request_id\)/)});
test('command transport retains explicit action, tenant-free payload and stable request token',async()=>{const api=load('lib/classes/data.ts'),calls=[];const client={rpc:async(name,args)=>{calls.push({name,args});return {data:{id:'p'},error:null}}};for(const action of ['save','publish','end','archive','restore','delete','change'])await api.classCommand(client,action,'p',{confirmation:'Example'},'request');assert.equal(calls.length,7);assert.ok(calls.every(c=>c.name==='classes_command'&&c.args.p_request_id==='request'&&!('club_id' in c.args)));await assert.rejects(()=>api.classCommand({rpc:async()=>({error:{message:'Class outside club'}})},'archive','other',{},'r'),/Class outside club/)});
test('matching JSON verifier fingerprints every replacement and internal helper without running commands',()=>{const verify=fs.readFileSync('supabase/verify_v1_7_2_classes_lifecycle.sql','utf8');for(const match of sql.matchAll(/create (?:or replace )?function public\.(\w+)\(.*?(\$\$|\$function\$)(.*?)\2\s*;/gis))assert.ok(verify.includes(crypto.createHash('md5').update(match[3]).digest('hex')),match[1]);assert.doesNotMatch(verify,/^\s*(insert|update|delete|alter|drop|create)\b/im);assert.match(verify,/old_loader_fallback_ghost_risk/);assert.match(verify,/null::uuid club_id/)});
test('new migration fails closed on drift and wraps snapshots, DDL and rollback assertions atomically',()=>{assert.match(sql,/set local lock_timeout='2s'/);assert.match(sql,/set local statement_timeout='60s'/);assert.match(sql,/Reviewed function drift/);assert.match(sql,/Class date constraint drift/);assert.ok(sql.indexOf('do $classes_lifecycle_migration$')<sql.indexOf('create temporary table'));assert.ok(sql.indexOf('end $classes_lifecycle_migration$;')>sql.indexOf('do $verify$'));assert.match(sql,/Direct class mutation privilege remains/)});
test('lifecycle form ignores duplicate submissions while a request is pending',async()=>{
 let release,calls=0,saved=0;const deferred=new Promise(resolve=>release=resolve);
 const mockReact={...React,useState:value=>[typeof value==='function'?value():value,()=>{}],useRef:value=>({current:value}),useEffect(){}};
 const Form=loader({react:mockReact,'@/lib/classes/data':{classCommand:async()=>{calls++;await deferred;return {id:'p'}},classDependencies:async()=>({allowed:true,blockers:[]})}})('components/classes/class-lifecycle.tsx').default;
 const element=Form({client:{},profile:fixture().profiles[0],action:'archive',data:fixture(),onClose(){},onSaved(){saved++}});
 const submit=element.props.children.props.onSubmit;submit({preventDefault(){}});submit({preventDefault(){}});assert.equal(calls,1);release();await new Promise(r=>setImmediate(r));assert.equal(saved,1);
});
test('archived library filter exposes repair/restore without exposing records in the default list',()=>{
 const d=fixture();d.profiles[0].active=false;d.profiles[0].archive_state={sessions:['c'],slots:[]};
 const Library=load('components/classes/class-library.tsx').default;assert.doesNotMatch(renderToStaticMarkup(React.createElement(Library,{data:d,loading:false,onOpen(){},onLifecycle(){}})),/>Example</);
 let state=0;const Archived=loader({react:{...React,useState:v=>[state++===1?'archived':v,()=>{}]}})('components/classes/class-library.tsx').default;
 const html=renderToStaticMarkup(Archived({data:d,loading:false,onOpen(){},onLifecycle(){}}));for(const text of ['Example','Archived','Repair archive','Restore','Open class'])assert.ok(html.includes(text));
});
