const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const loader=require('./load-typescript.cjs');
const m=loader()('lib/classes/model.ts');
function fixture(){return {profiles:[{id:'p',name:'Class',active:true,publication_status:'published',visibility:'internal',start_date:null,end_date:null,category_id:'cat',programme_id:'prog',session_colour:'#111111'}],sessions:[{id:'c',class_profile_id:'p',venue_id:'v',weekday:1,start_time:'16:00',finish_time:'17:00',active:true}],categories:[{id:'cat',colour:'#222222'}],programmes:[{id:'prog',category_id:'cat',colour:'#333333'}],slots:[{id:'s1',class_id:'c',active:true},{id:'s2',class_id:'c',active:true}],shifts:[],exclusions:[],venues:[],activity:[]}}
test('weekly date arithmetic remains stable over DST and year boundaries',()=>{assert.deepEqual(m.calendarRange('2026-03-29','week'),{from:'2026-03-23',to:'2026-03-29'});assert.equal(m.addDays('2026-12-31',1),'2027-01-01');assert.equal(m.addDays('2026-03-29',1),'2026-03-30')});
test('calendar expands recurrence within inclusive date bounds, without generated shifts',()=>{const d=fixture();d.profiles[0].start_date='2026-09-14';d.profiles[0].end_date='2026-09-21';const e=m.expandCalendar(d,'2026-09-01','2026-09-30');assert.deepEqual(e.map(x=>x.date),['2026-09-14','2026-09-21']);assert.equal(e[0].colour,'#333333');assert.equal(e[0].coverage,'unknown')});
test('drafts are visible in Classes and archive filter is explicit',()=>{const d=fixture();d.profiles[0].publication_status='draft';assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07').length,1);d.profiles[0].active=false;assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07').length,0);assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07',{...m.emptyFilters,status:'archived'}).length,1)});
test('whole occurrence exclusions remove events; partial exclusions retain the class',()=>{const d=fixture();d.exclusions=[{class_id:'c',shift_date:'2026-09-07',staffing_slot_id:'s1'}];let e=m.expandCalendar(d,'2026-09-07','2026-09-07');assert.equal(e.length,1);assert.equal(e[0].required,1);assert.equal(e[0].excludedSlots,1);d.exclusions.push({class_id:'c',shift_date:'2026-09-07',staffing_slot_id:'s2'});assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07').length,0);d.exclusions=[{class_id:'c',shift_date:'2026-09-07',staffing_slot_id:null}];assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07').length,0)});
test('coverage is unknown for partial generation, then covered/understaffed/cancelled',()=>{const d=fixture();const row={class_id:'c',shift_date:'2026-09-07',assigned:true,status:'scheduled'};d.shifts=[{...row,staffing_slot_id:'s1'}];const coverage=()=>m.expandCalendar(d,'2026-09-07','2026-09-07')[0].coverage;assert.equal(coverage(),'unknown');d.shifts.push({...row,staffing_slot_id:'s2'});assert.equal(coverage(),'covered');d.shifts[1].assigned=false;assert.equal(coverage(),'understaffed');d.shifts.forEach(s=>s.status='cancelled');assert.equal(coverage(),'cancelled')});
test('inactive slots and retired recurrences never contribute new staffing coverage',()=>{const d=fixture();d.slots[1].active=false;d.shifts=[{class_id:'c',shift_date:'2026-09-07',staffing_slot_id:'s1',assigned:true,status:'confirmed'}];assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07')[0].coverage,'covered');d.sessions[0].active=false;assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07').length,0)});
test('all calendar filters operate on the shared profile/session model',()=>{const d=fixture();for(const filter of [{category:'other'},{programme:'other'},{venue:'other'},{visibility:'public'},{status:'draft'},{coverage:'covered'}])assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07',{...m.emptyFilters,...filter}).length,0)});
test('calendar opening only calls the read RPC; saves and publication are explicit and isolated',async()=>{const api=loader()('lib/classes/data.ts'),calls=[];const mock={rpc:async(name,args)=>{calls.push({name,args});return {data:fixture(),error:null}}};await api.loadCalendar(mock,'2026-09-07','2026-09-13');assert.deepEqual(calls.map(c=>c.name),['classes_calendar_data']);await api.saveClass(mock,{id:'p'},null);await api.publishClass(mock,'p');assert.deepEqual(calls.map(c=>c.name),['classes_calendar_data','classes_save_profile','classes_publish']);assert.equal(calls[1].args.p_sessions,null)});
test('read failures are surfaced instead of showing false staffing confidence',async()=>{const api=loader()('lib/classes/data.ts');await assert.rejects(()=>api.loadCalendar({rpc:async()=>({data:null,error:{message:'Unavailable'}})},'2026-09-07','2026-09-13'),/Unavailable/)});
test('console preserves accepted Schedule Control shell and accessible close',()=>{const React=require('react');const {renderToStaticMarkup}=require('react-dom/server');const Console=loader()('components/classes/class-console.tsx').default;const html=renderToStaticMarkup(React.createElement(Console,{title:'Test class',status:'draft · internal',onClose(){}},'Content'));for(const token of ['v311AdminShiftHero','v405ScheduleControlBody','v405ScheduleControlFoot','Close class console','Class Console'])assert.ok(html.includes(token))});
test('forward migration has transaction, drift guard, preservation assertions and no operational DML calls',()=>{const sql=fs.readFileSync('supabase/v1_7_0_classes_phase_1.sql','utf8');assert.match(sql,/begin;\nset local lock_timeout='2s'/);assert.match(sql,/md5\(pg_get_functiondef/);assert.match(sql,/n<>b.row_count or h<>b.fingerprint/);assert.match(sql,/add column publication_status text not null default 'published'/);assert.match(sql,/alter column publication_status set default 'draft'/);assert.doesNotMatch(sql,/perform public\.(sync_class_schedule|generate_schedule_month)/i);assert.doesNotMatch(sql,/create or replace function public\.(clone|copy|confirm|cancel|sync)/i);assert.match(sql,/before delete on public.class_staffing_slots/);assert.match(sql,/set active=false where class_id=sid/)});
test('new Classes UI does not call legacy schedule mutation functions',()=>{for(const file of ['components/classes/classes-view.tsx','lib/classes/data.ts']){const s=fs.readFileSync(file,'utf8');assert.doesNotMatch(s,/clone_schedule_month|sync_class_schedule|generate_schedule_month/)}const s=fs.readFileSync('components/classes/classes-view.tsx','utf8');assert.match(s,/draft.publication_status==='published'\?null:sessions/);assert.match(s,/if\(!confirm\(`Publish/)});
test('dated staffing overrides are not advertised as verified recurrence coverage',()=>{const d=fixture();d.shifts=d.slots.map(s=>({class_id:'c',shift_date:'2026-09-07',staffing_slot_id:s.id,assigned:true,status:'scheduled',start_time:'18:00',finish_time:'19:00',venue_id:'v'}));assert.equal(m.expandCalendar(d,'2026-09-07','2026-09-07')[0].coverage,'unknown')});
test('post-migration verification fingerprints match the shipped function bodies',()=>{const crypto=require('node:crypto'),sql=fs.readFileSync('supabase/v1_7_0_classes_phase_1.sql','utf8'),verify=fs.readFileSync('supabase/verify_v1_7_0_classes_phase_1.sql','utf8');for(const match of sql.matchAll(/create function public\.(\w+)\(.*?as \$\$(.*?)\$\$;/gis)){const hash=crypto.createHash('md5').update(match[2]).digest('hex');assert.ok(verify.includes(hash),match[1])}});
test('generator differs from the reviewed production body only by eligibility predicates',()=>{const crypto=require('node:crypto'),sql=fs.readFileSync('supabase/v1_7_0_classes_phase_1.sql','utf8');let definition=sql.match(/CREATE OR REPLACE FUNCTION public.generate_schedule_month[\s\S]*?AS \$function\$[\s\S]*?\$function\$\n/)[0];definition=definition.replace("\n      and exists (select 1 from public.class_profiles p where p.id=classes.class_profile_id and p.publication_status='published')",'').replace(' and exists (select 1 from public.class_profiles p where p.id=c.class_profile_id and (p.start_date is null or d>=p.start_date) and (p.end_date is null or d<=p.end_date))','').replace('where class_id = c.id and active','where class_id = c.id');assert.equal(crypto.createHash('md5').update(definition).digest('hex'),'fb587e691fc64783e7117e159991c68e')});
test('Master Timetable requirement-only changes preserve inactive defaults and skip shift sync',()=>{const s=fs.readFileSync('app/dashboard/ui.tsx','utf8');assert.match(s,/existing\?\.active===false\?existing.default_profile_id:null/);assert.match(s,/existingSlots.some\(slot=>slot.active!==false&&slot.slot_number<=required/);assert.match(s,/if\(scheduleChanged\)\{\s*const\{error:syncError\}/);assert.match(s,/!requirementsChanged\|\|scheduleChanged/)});
test('temporary migration baselines are created and verified within one atomic block',()=>{const sql=fs.readFileSync('supabase/v1_7_0_classes_phase_1.sql','utf8');const start=sql.indexOf('do $classes_phase1_migration$'),end=sql.lastIndexOf('$classes_phase1_migration$;');assert.ok(start>0&&end>start);for(const name of ['classes_phase1_scheduled_baseline','classes_phase1_baseline']){const create=sql.indexOf('create temporary table pg_temp.'+name);assert.ok(create>start&&create<sql.indexOf('do $baseline_preflight$'));assert.ok(sql.includes("to_regclass('pg_temp."+name+"') is null"));assert.doesNotMatch(sql,new RegExp('(?:from|into) '+name+'\\b','i'))}assert.ok(sql.indexOf('do $verify$')<end);assert.equal((sql.match(/on commit drop/g)||[]).length,2);assert.match(sql,/\$classes_phase1_migration\$;\ncommit;/)});
test('baseline validation fails closed and retains both directions of EXCEPT plus complete fingerprints',()=>{const sql=fs.readFileSync('supabase/v1_7_0_classes_phase_1.sql','utf8'),verify=sql.slice(sql.indexOf('do $verify$'));assert.ok(verify.indexOf("to_regclass('pg_temp.classes_phase1_scheduled_baseline')")<verify.indexOf('if exists((select *'));assert.match(verify,/count\(\*\) from pg_temp.classes_phase1_baseline\)<>9/);assert.match(verify,/public.scheduled_shifts except select \* from pg_temp.classes_phase1_scheduled_baseline/);assert.match(verify,/pg_temp.classes_phase1_scheduled_baseline except select \* from public.scheduled_shifts/);assert.match(verify,/n<>b.row_count or h<>b.fingerprint/);assert.doesNotMatch(verify,/create temporary table/)});
test('Month ranges and navigation handle leap years and six-week months',()=>{assert.deepEqual(m.calendarRange('2026-08-15','month'),{from:'2026-07-27',to:'2026-09-06'});assert.deepEqual(m.calendarRange('2028-02-20','month'),{from:'2028-01-31',to:'2028-03-05'});assert.equal(m.moveCalendar('2026-01-31','month',1),'2026-02-01')});
test('Week rows group profile identity, earliest time first, alphabetical ties, empty cells and stacked sessions',()=>{
 const dates=Array.from({length:7},(_,i)=>m.addDays('2026-09-07',i));
 const e=(id,name,date,time,key)=>({key,profile:{id,name},date,session:{class_profile_id:id,start_time:time}});
 const rows=m.weekRows([e('t','Tots',dates[0],'16:00','1'),e('t','Tots',dates[1],'16:00','2'),e('t','Tots',dates[5],'10:30','3'),e('t','Tots',dates[0],'17:00','4'),e('a','Alpha',dates[2],'10:30','5'),e('other','Tots',dates[0],'18:00','6')],dates);
 assert.deepEqual(rows.map(r=>r.id),['a','t','other']);assert.equal(rows[1].cells[2].length,0);assert.deepEqual(rows[1].cells[0].map(e=>e.session.start_time),['16:00','17:00']);assert.equal(rows[1].cells[5][0].session.start_time,'10:30');
});
test('Day/List expansion orders time before name, independent of recurrence input order',()=>{const d=fixture();d.profiles.push({...d.profiles[0],id:'p2',name:'Alpha'});d.sessions.push({...d.sessions[0],id:'c2',class_profile_id:'p2'},{...d.sessions[0],id:'c3',start_time:'09:00'});assert.deepEqual(m.expandCalendar(d,'2026-09-07','2026-09-07').map(e=>e.session.id),['c3','c2','c'])});
test('complete Draft payload stays in one save RPC and publication stays separate',async()=>{
 const api=loader()('lib/classes/data.ts'),calls=[];const client={rpc:async(name,args)=>{calls.push({name,args});return {data:'draft-id',error:null}}};
 const profile={name:'Greenhead fixture',capacity:12,session_colour:'#123456',minimum_coaches:1,maximum_coaches:3,lead_coaches_required:1,assistant_coaches_required:1,required_coaches:2,publication_status:'draft',visibility:'internal',session_length_minutes:60,start_date:'2026-09-07',description:'Description',eligibility_description:'Eligibility',category_id:'cat',programme_id:'prog',minimum_age:4,maximum_age:8,warn_if_understaffed:true,critical_if_no_lead:true,allow_below_recommended_qualification:false,lead_recommended_qualification_id:'q'};
 const sessions=[{weekday:1,start_time:'16:00',venue_id:'v',break_minutes:5,notes:'Notes',staffing:[{slot_number:1,default_profile_id:'coach',payment_type:'enhanced'}]}];
 assert.equal(loader()('lib/classes/draft.ts').validateDraft(profile,sessions),'');await api.saveClass(client,profile,sessions);assert.deepEqual(calls,[{name:'classes_save_profile',args:{p_data:profile,p_sessions:sessions}}]);await api.publishClass(client,'draft-id');assert.equal(calls[1].name,'classes_publish');
});
test('creation upgrade preserves generator and published schedule safeguards',()=>{const sql=fs.readFileSync('supabase/v1_7_1_classes_creation.sql','utf8');assert.doesNotMatch(sql,/create or replace function public.generate_schedule_month|insert into public.scheduled_shifts|update public.(scheduled_shifts|shifts|timesheets|invoices)|perform public./i);assert.match(sql,/p.publication_status='published' and p_sessions is not null/);assert.match(sql,/Published timing and date changes require/);assert.match(sql,/id=coach and club_id=cid and is_active/);assert.match(sql,/default_payment_type/);assert.match(sql,/'creation_version',2/)});
test('Load shifts retains inclusive eligibility, active slots, idempotency and exclusion gates',()=>{
 const sql=fs.readFileSync('supabase/v1_7_0_classes_phase_1.sql','utf8');const generator=sql.slice(sql.indexOf('CREATE OR REPLACE FUNCTION public.generate_schedule_month'),sql.indexOf('-- Scoped ACL-only hardening'));
 for(const pattern of [/publication_status='published'/,/d>=p.start_date/,/d<=p.end_date/,/where class_id = c.id and active/,/on conflict \(staffing_slot_id, shift_date\) do nothing/])assert.match(generator,pattern);
 assert.match(sql,/tgname='trg_skip_excluded_scheduled_occurrence' and tgenabled='O'/);
 const publish=sql.slice(sql.indexOf('create function public.classes_publish'),sql.indexOf('-- Read only RPC'));
 assert.doesNotMatch(publish,/scheduled_shifts|generate_schedule_month|sync_class_schedule/);
});
test('creation verification matches both replacement RPC bodies and remains read-only',()=>{
 const crypto=require('node:crypto'),sql=fs.readFileSync('supabase/v1_7_1_classes_creation.sql','utf8'),verify=fs.readFileSync('supabase/verify_v1_7_1_classes_creation.sql','utf8');for(const match of sql.matchAll(/create or replace function public\.(\w+)\(.*?as \$\$(.*?)\$\$;/gis))assert.ok(verify.includes(crypto.createHash('md5').update(match[2]).digest('hex')),match[1]);assert.doesNotMatch(verify,/^\s*(insert|update|delete|alter|create|drop)\b/im);
});
