// Synthetic fixtures only. Start Chrome with --headless --remote-debugging-port=9334.
const fs=require('node:fs'),assert=require('node:assert/strict'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),loader=require('./load-typescript.cjs');
const context={today:'2026-09-17',counts:{active:4,trial:2,waiting:3},athletes:[{id:'athlete',family_id:'family',display_name:'Synthetic Athlete With A Long Name',family_name:'Synthetic Family Account',status:'active'}],profiles:[{id:'profile',name:'Recreational Gymnastics',active:true,publication_status:'published',capacity:12,start_date:null,end_date:null}],sessions:[0,1,2].map((n)=>({id:`session-${n}`,class_profile_id:'profile',weekday:n+1,start_time:`1${n}:00`,finish_time:`1${n+1}:00`,venue_id:'venue',venue_name:'Synthetic Community Sports Centre',capacity:12,active:true,effective_from:null,effective_to:null,occupied_today:n,occupancy:[]})),enrolments:[]};
const Form=loader({'@/lib/supabase/client':{createClient:()=>({})},'./enrolments.css':{}})('components/enrolments/enrolments-panel.tsx').EnrolmentForm;
const markup=renderToStaticMarkup(React.createElement(Form,{context,profileId:'profile',search:'',onSearch(){},onCancel(){},onSaved(){}}));
(async()=>{const targets=await fetch('http://127.0.0.1:9334/json').then(r=>r.json()),ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map();ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id){const p=pending.get(message.id);pending.delete(message.id);message.error?p.reject(message.error):p.resolve(message.result)}});const call=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});const run=async expression=>{const result=await call('Runtime.evaluate',{expression,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value};
 const css=fs.readFileSync('app/globals.css','utf8')+fs.readFileSync('components/classes/classes.css','utf8')+fs.readFileSync('components/enrolments/enrolments.css','utf8');const results=[];
 for(const width of [375,1280]){await call('Emulation.setDeviceMetricsOverride',{width,height:800,deviceScaleFactor:1,mobile:width<600});await call('Page.enable');await call('Page.setDocumentContent',{frameId:(await call('Page.getFrameTree')).frameTree.frame.id,html:`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><main class="main"><div class="classesConsole" style="display:block;width:${width<600?'100%':'820px'};height:780px;overflow:auto">${markup}</div></main>`});const layout=await run(`(()=>{const root=document.querySelector('.enrolmentEditor'),rr=root.getBoundingClientRect();return {pageOverflow:document.documentElement.scrollWidth>innerWidth,rootOverflow:root.scrollWidth>root.clientWidth,left:rr.left,right:rr.right,buttons:[...root.querySelectorAll('button')].map(b=>b.getBoundingClientRect().height),inputs:[...root.querySelectorAll('input:not([type=checkbox]),select,textarea')].map(i=>i.getBoundingClientRect().width)}})()`);assert.equal(layout.pageOverflow,false,JSON.stringify(layout));assert.equal(layout.rootOverflow,false,JSON.stringify(layout));assert.ok(layout.left>=0&&layout.right<=width+1,JSON.stringify(layout));if(width===375)for(const height of layout.buttons)assert.ok(height>=42,JSON.stringify(layout));for(const inputWidth of layout.inputs)assert.ok(inputWidth>100,JSON.stringify(layout));results.push({width,...layout})}
 console.log(JSON.stringify(results,null,2));ws.close()})().catch(error=>{console.error(error);process.exitCode=1});
