// Synthetic fixtures only. Start Chrome with --headless --remote-debugging-port=9334.
const fs=require('node:fs'),assert=require('node:assert/strict'),React=require('react'),{renderToStaticMarkup}=require('react-dom/server'),loader=require('./load-typescript.cjs');
const Identity=loader()('components/club-identity.tsx').default;
const css=fs.readFileSync('app/globals.css','utf8');
const cases=[
  {name:'A very long Greenhead Gymnastics club name used for truncation',logoUrl:null,primaryColour:'#245f9e'},
  {name:'Greenhead Gymnastics',logoUrl:'https://cdn.example.test/broken-logo.png',primaryColour:'#245f9e'},
  {name:'Greenhead Gymnastics',logoUrl:'https://cdn.example.test/square-logo.png',primaryColour:'#245f9e'},
  {name:'Kirklees Gymnastics Centre',logoUrl:'https://pbs.twimg.com/profile_images/example.png?format=jpg&name=small',primaryColour:'#62923a'}
];
 (async()=>{const targets=await fetch('http://127.0.0.1:9334/json').then(r=>r.json()),ws=new WebSocket(targets.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map();ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id){const p=pending.get(message.id);pending.delete(message.id);message.error?p.reject(message.error):p.resolve(message.result)}});const call=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});const run=async expression=>{const result=await call('Runtime.evaluate',{expression,returnByValue:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value};
 const results=[];for(const viewport of [{width:375,index:0},{width:375,index:1},{width:375,index:2},{width:1280,index:3}]){const {width,index}=viewport;await call('Emulation.setDeviceMetricsOverride',{width,height:800,deviceScaleFactor:1,mobile:width<600});await call('Page.enable');const markup=renderToStaticMarkup(React.createElement(Identity,{...cases[index]}));await call('Page.setDocumentContent',{frameId:(await call('Page.getFrameTree')).frameTree.frame.id,html:`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><main class="portal"><header class="topbar"><div class="row v3TopbarIdentity">${markup}</div><span class="versionBadge">v5.1</span></header></main>`});const layout=await run(`(()=>{const el=document.querySelector('.clubIdentity'),m=document.querySelector('.clubIdentityMark'),name=el.querySelector('strong'),r=el.getBoundingClientRect(),mr=m.getBoundingClientRect();return {pageOverflow:document.documentElement.scrollWidth>innerWidth,left:r.left,right:r.right,width:r.width,markWidth:mr.width,markHeight:mr.height,hasImage:Boolean(el.querySelector('img')),nameOverflow:Boolean(name&&name.scrollWidth>name.clientWidth)}})()`);assert.equal(layout.pageOverflow,false,JSON.stringify(layout));assert.equal(layout.hasImage,false,JSON.stringify(layout));assert.equal(layout.markWidth,40,JSON.stringify(layout));assert.equal(layout.markHeight,40,JSON.stringify(layout));assert.ok(layout.left>=0&&layout.right<=width+1,JSON.stringify(layout));results.push({width,index,...layout})}console.log(JSON.stringify(results,null,2));ws.close()})().catch(error=>{console.error(error);process.exitCode=1});
