'use client';
import {useState} from 'react';
import {classState} from '@/lib/classes/lifecycle';
import {today,type CalendarData,type ClassProfile} from '@/lib/classes/model';
const days=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
export type LifecycleAction='end'|'archive'|'restore'|'delete'|'change';
export default function ClassLibrary({data,loading,onOpen,onLifecycle}:{data:CalendarData|null;loading:boolean;onOpen:(p:ClassProfile|undefined,mode:'view'|'edit')=>void;onLifecycle:(p:ClassProfile,action:LifecycleAction)=>void}){
 const [search,setSearch]=useState(''),[state,setState]=useState('active'),[category,setCategory]=useState(''),[programme,setProgramme]=useState(''),[venue,setVenue]=useState('');
 const profiles=data?.profiles.filter(p=>{const status=classState(p);return p.name.toLowerCase().includes(search.trim().toLowerCase())&&(state==='all'||state==='active'?state==='all'||status!=='archived':state===status)&&(!category||p.category_id===category)&&(!programme||p.programme_id===programme)&&(!venue||data.sessions.some(s=>s.class_profile_id===p.id&&s.venue_id===venue))})||[];
 return <section aria-label="Class Library"><header className="classesHeader"><div><h1>Class Library</h1><p>Manage classes, weekly sessions and their lifecycle.</p></div><button className="btn btnPrimary" disabled={!data||loading} onClick={()=>onOpen(undefined,'edit')}>Create Draft</button></header>
 <div className="classesLibraryFilters"><label>Search classes<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Class name"/></label><label>State<select value={state} onChange={e=>setState(e.target.value)}>{[['active','Current and ended'],['all','All classes'],['draft','Draft'],['published','Published'],['ended','Ended'],['archived','Archived']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{data?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Programme<select value={programme} onChange={e=>setProgramme(e.target.value)}><option value="">All programmes</option>{data?.programmes.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Venue<select value={venue} onChange={e=>setVenue(e.target.value)}><option value="">All venues</option>{data?.venues.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label></div>
 {loading?<p role="status">Loading classes…</p>:!data?<p>The Class Library is unavailable.</p>:<div className="classesLibraryRows">{profiles.sort((a,b)=>a.name.localeCompare(b.name)).map(p=>{const status=classState(p),programme=data.programmes.find(x=>x.id===p.programme_id),category=data.categories.find(x=>x.id===(p.category_id||programme?.category_id));const sessions=data.sessions.filter(s=>s.class_profile_id===p.id&&(status==='archived'||s.active)).sort((a,b)=>a.weekday-b.weekday||a.start_time.localeCompare(b.start_time));return <article className="classesLibraryRow" key={p.id} style={{borderLeftColor:programme?.colour||category?.colour||p.session_colour}}><div className="classesLibraryIdentity"><h2>{p.name}</h2><p>{[category?.name,programme?.name||p.programme].filter(Boolean).join(' · ')||'Uncategorised'}</p><span className={`classesBadge classesBadge-${status}`}>{status[0].toUpperCase()+status.slice(1)}</span> <span className="classesBadge">{p.visibility==='public'?'Public':'Internal'}</span></div><div><strong>Weekly sessions</strong>{sessions.map(s=><p key={s.id}>{days[s.weekday]} {s.start_time.slice(0,5)}–{s.finish_time.slice(0,5)} · {data.venues.find(v=>v.id===s.venue_id)?.name||'Venue unavailable'}{s.effective_from?` · from ${s.effective_from}`:''}{s.effective_to?` · through ${s.effective_to}`:''}{s.effective_to&&s.effective_to<today()?' · Historical':''}</p>)}{!sessions.length&&<p>No active weekly sessions</p>}</div><div><p>Capacity {p.capacity} · Ages {p.minimum_age??'Any'}–{p.maximum_age??'Any'}</p><p>{p.eligibility_description||'No additional eligibility'}</p><p>{p.lead_coaches_required} lead + {p.assistant_coaches_required} assistant · {p.minimum_coaches??1}–{p.maximum_coaches??1} coaches</p><p>{p.start_date||'Open start'} → {p.end_date||'No final date'} (inclusive)</p></div><div className="classesLibraryActions"><button className="btn btnSecondary" onClick={()=>onOpen(p,'view')}>View</button>{status!=='archived'&&<button className="btn btnSecondary" onClick={()=>onOpen(p,'edit')}>Edit</button>}{p.active&&p.publication_status==='published'&&<><button className="btn btnSecondary" onClick={()=>onLifecycle(p,'end')}>End class</button><button className="btn btnSecondary" onClick={()=>onLifecycle(p,'change')}>Change from date</button></>}{p.active?<button className="btn btnSecondary" onClick={()=>onLifecycle(p,'archive')}>Archive</button>:<><button className="btn btnSecondary" onClick={()=>onLifecycle(p,'archive')}>Repair archive</button><button className="btn btnSecondary" disabled={!p.archive_state?.sessions.length} onClick={()=>onLifecycle(p,'restore')}>Restore</button></>}{p.publication_status==='draft'&&<button className="btn btnSecondary" onClick={()=>onLifecycle(p,'delete')}>Permanently delete…</button>}</div></article>})}{!profiles.length&&<p>No classes match these filters.</p>}</div>}
 </section>;
}
