'use client';
import './classes.css';
import {useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {createClient} from '@/lib/supabase/client';
import {classCommand,loadCalendar,saveTaxonomy} from '@/lib/classes/data';
import {calendarRange,emptyFilters,expandCalendar,today,type CalendarData,type ClassProfile,type Session,type Category,type Programme} from '@/lib/classes/model';
import {publishedDefaultsChanged,safeProfilePayload} from '@/lib/classes/editor';
import {validateDraft} from '@/lib/classes/draft';
import {classSections} from '@/lib/classes/lifecycle';
import ClassLibrary,{type LifecycleAction} from './class-library';
import ClassLifecycle from './class-lifecycle';
import ClassConsole from './class-console';
import ClassCalendar from './class-calendar';
import EnrolmentsPanel from '@/components/enrolments/enrolments-panel';
function finishTime(start:string,duration:number){const [h,m]=start.split(':').map(Number);const t=(h*60+m+duration)%1440;return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`}
const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
const tabs=['Overview','Schedule','Capacity and eligibility','Staffing','Roster','Activity'] as const;
type Draft=Omit<ClassProfile,'id'>&{id?:string;required_coaches:number};
function newDraft():Draft{return {name:'',active:true,publication_status:'draft',visibility:'internal',category_id:null,programme_id:null,start_date:today(),end_date:null,capacity:12,minimum_age:null,maximum_age:null,session_length_minutes:60,lead_coaches_required:1,assistant_coaches_required:0,description:'',eligibility_description:'',session_colour:'#6D3A91',minimum_coaches:1,maximum_coaches:1,warn_if_understaffed:true,critical_if_no_lead:true,allow_below_recommended_qualification:true,required_coaches:1}}
export default function ClassesView({initialProfileId,onOpened,overlay=false,canEdit=true,onClose,onSaved,onOpenInClasses}:{initialProfileId?:string|null;onOpened?:()=>void;overlay?:boolean;canEdit?:boolean;onClose?:()=>void;onSaved?:(data:CalendarData)=>void;onOpenInClasses?:()=>void}){
 const [mode,setMode]=useState<'view'|'edit'>('view');
 const [section,setSection]=useState<typeof classSections[number]>('Class Library');
 const [lifecycle,setLifecycle]=useState<{profile:ClassProfile;action:LifecycleAction}|null>(null);
 const request=useRef<string|null>(null);
 const client=useMemo(()=>createClient(),[]);const [anchor,setAnchor]=useState(today);const [view,setView]=useState<'month'|'week'|'day'|'list'>('week');const [filters,setFilters]=useState(emptyFilters);
 const [data,setData]=useState<CalendarData|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
 const [draft,setDraft]=useState<Draft|null>(null),[sessions,setSessions]=useState<Partial<Session>[]>([]),[tab,setTab]=useState<typeof tabs[number]>('Overview'),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false);
 const [taxonomy,setTaxonomy]=useState<{kind:'category'|'programme';data:Partial<Category&Programme>}|null>(null);
 const openedProfile=useRef<string|null>(null);
 const sequence=useRef(0),flight=useRef(false);const range=calendarRange(anchor,view);
 useEffect(()=>{const id=++sequence.current;setLoading(true);if(!overlay)setData(null);setError('');loadCalendar(client,range.from,range.to).then(value=>{if(sequence.current===id)setData(value)}).catch(e=>{if(sequence.current===id)setError(e.message)}).finally(()=>{if(sequence.current===id)setLoading(false)});return()=>{sequence.current++}},[client,range.from,range.to,revision]);
 const events=data?expandCalendar(data,range.from,range.to,filters):[];
 useEffect(()=>{if(initialProfileId&&data&&openedProfile.current!==initialProfileId){const p=data.profiles.find(p=>p.id===initialProfileId);if(p){openedProfile.current=initialProfileId;open(p,'view')}else setError('This class is unavailable in your club.');onOpened?.()}},[initialProfileId,data,onOpened]);
 useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(''),4500);return()=>window.clearTimeout(timer)},[notice]);
 function open(profile:ClassProfile|undefined,mode:'view'|'edit',source=data){setMode(canEdit?mode:'view');request.current=null;setTab('Overview');setDirty(false);setError('');setDraft(profile?{...profile,required_coaches:profile.lead_coaches_required+profile.assistant_coaches_required}:newDraft());setSessions(profile?source!.sessions.filter(s=>s.class_profile_id===profile.id&&(s.active||!profile.active)).map(s=>({...s,staffing:source!.slots.filter(slot=>slot.class_id===s.id&&slot.active).map(slot=>({slot_number:slot.slot_number,default_profile_id:slot.default_profile_id||null,payment_type:slot.payment_type||'standard'}))})):[{venue_id:source?.venues.find(v=>v.active)?.id||'',weekday:1,start_time:'16:30',break_minutes:0}])}
 function updateSlot(index:number,number:number,change:Partial<import('@/lib/classes/model').StaffingDefault>){setSessions(current=>current.map((s,i)=>i===index?{...s,staffing:[...(s.staffing||[]).filter(x=>x.slot_number!==number),{slot_number:number,default_profile_id:null,payment_type:'standard',...s.staffing?.find(x=>x.slot_number===number),...change}]}:s));request.current=null;setDirty(true)}
 function close(){if(!busy&&(!dirty||confirm('Discard unsaved class changes?'))){setDraft(null);setDirty(false);onClose?.()}}
 function patch(change:Partial<Draft>){request.current=null;setDraft(d=>d?{...d,...change}:d);setDirty(true)}
 async function action(work:()=>Promise<void>){if(flight.current)return;flight.current=true;setBusy(true);setError('');try{await work()}catch(e){setError(e instanceof Error?e.message:'Unable to save')}finally{flight.current=false;setBusy(false)}}
 function save(e:FormEvent){e.preventDefault();if(!canEdit||!draft||mode!=='edit'||draft.active===false)return;if(draft.publication_status==='published'&&data?.editing_version!==1&&publishedDefaultsChanged(sessions,data?.slots||[])){setError('Saving published staffing defaults requires the reviewed Classes editor upgrade. Your changes have not been saved.');return}if(data?.lifecycle_version!==3){setError('Class management requires the Classes lifecycle upgrade. Ask your administrator to review and apply it first.');return}const validation=validateDraft(draft,sessions);if(validation){setError(validation);return}void action(async()=>{request.current??=crypto.randomUUID();const result=await classCommand(client,'save',draft.id||null,{profile:safeProfilePayload(draft,sessions,data?.editing_version===1),sessions:draft.publication_status==='published'?null:sessions},request.current);setDraft({...draft,id:result.id});setSessions(result.sessions);setDirty(false);request.current=null;setNotice('Class saved. Existing staff shifts are unchanged.');await refreshSavedClass()})}
 async function refreshSavedClass(reopen=false){if(!overlay){setRevision(n=>n+1);return}try{const refreshed=await loadCalendar(client,range.from,range.to);setData(refreshed);setError('');if(reopen){const profile=refreshed.profiles.find(p=>p.id===initialProfileId);if(profile)open(profile,'view',refreshed)}onSaved?.(refreshed)}catch(e){setError(`Class saved, but timetable refresh failed: ${e instanceof Error?e.message:'Please reload class data.'}`)}}
 function publish(){if(!draft?.id||dirty)return;if(!confirm(`Publish ${draft.name} to Master Timetable?\n\nThis does not generate staff shifts. Generate or update the relevant staff schedule separately.`))return;void action(async()=>{await classCommand(client,'publish',draft.id!,{},crypto.randomUUID());setDraft({...draft,publication_status:'published'});setNotice('Published to Master Timetable. Generate or update the relevant staff schedule separately.');setRevision(n=>n+1)})}
 function taxonomySave(e:FormEvent){e.preventDefault();if(!taxonomy)return;void action(async()=>{await saveTaxonomy(client,taxonomy.kind,{...taxonomy.data});setTaxonomy(null);setRevision(n=>n+1);setNotice('Club taxonomy saved.')})}
 const published=draft?.publication_status==='published';
 const readOnly=!canEdit||mode==='view'||draft?.active===false;
 return <section className="classesWorkspace">
  {!overlay&&notice&&<p role="status" className="notice">{notice}</p>}{error&&!draft&&!taxonomy&&<p role="alert" className="notice">{error}</p>}
  {!overlay&&<><nav className="classesTabs" aria-label="Classes sections">{classSections.map(item=><button type="button" key={item} aria-pressed={section===item} onClick={()=>setSection(item)}>{item}</button>)}</nav>
  {section==='Class Library'&&<ClassLibrary data={data} loading={loading} onOpen={open} onLifecycle={(profile,action)=>setLifecycle({profile,action})}/>}
  {section==='Timetable'&&<ClassCalendar data={data} events={events} loading={loading} anchor={anchor} view={view} filters={filters} from={range.from} to={range.to} onAnchor={setAnchor} onView={setView} onFilters={setFilters} onOpen={p=>open(p,'view')}/>}
  {section==='Categories & Programmes'&&!loading&&data&&<div className="classesManagement">
  <details open className="card classesLibrary"><summary>Manage categories and programmes</summary><div className="row"><button className="btn btnSecondary" onClick={()=>setTaxonomy({kind:'category',data:{name:'',colour:'#6D3A91',display_order:0,active:true}})}>Add category</button><button className="btn btnSecondary" onClick={()=>setTaxonomy({kind:'programme',data:{name:'',colour:'#6D3A91',active:true,category_id:null,description:''}})}>Add programme</button></div>{data.categories.map(c=><button key={c.id} className="btn btnSecondary" onClick={()=>setTaxonomy({kind:'category',data:c})}>{c.name} · Category{!c.active?' · Archived':''}</button>)}{data.programmes.map(p=><button key={p.id} className="btn btnSecondary" onClick={()=>setTaxonomy({kind:'programme',data:p})}>{p.name} · Programme{!p.active?' · Archived':''}</button>)}</details></div>}
  </>}
  {overlay&&!draft&&!lifecycle&&<ClassConsole title="Class Console" status={loading?'Loading class…':'Class unavailable'} onClose={()=>onClose?.()} footer={<button type="button" className="btn btnSecondary" onClick={()=>onClose?.()}>Back to previous page</button>}><p role={error?'alert':'status'}>{error||'Loading the complete class profile…'}</p></ClassConsole>}
  {lifecycle&&data&&<ClassLifecycle client={client} data={data} profile={lifecycle.profile} action={lifecycle.action} onClose={()=>{setLifecycle(null);if(overlay){const p=data.profiles.find(p=>p.id===initialProfileId);if(p)open(p,'view')}}} onSaved={()=>{setLifecycle(null);if(overlay){const p=data.profiles.find(p=>p.id===initialProfileId);if(p)open(p,'view');void refreshSavedClass(true);return}setNotice('Class updated. Existing dated records are unchanged.');setRevision(n=>n+1)}}/>}
  {draft&&<ClassConsole title={draft.name||'New class'} status={`${draft.active?(published?'Published':'Draft'):'Archived'} · ${draft.visibility==='public'?'Public':'Internal'}`} onClose={close} footer={!readOnly?<><button type="button" className="btn btnSecondary" disabled={busy} onClick={close}>Cancel</button><button form="classes-edit-form" type="submit" className="btn btnPrimary" disabled={busy}>{busy?'Saving…':'Save changes'}</button></>:<><button type="button" className="btn btnSecondary" onClick={close}>{overlay?'Back to previous page':'Back to Classes'}</button>{canEdit&&draft.active&&<button type="button" className="btn btnPrimary" onClick={()=>setMode('edit')}>Edit class</button>}{onOpenInClasses&&<button type="button" className="btn btnSecondary" onClick={onOpenInClasses}>Open in Classes</button>}</>}>
   {overlay&&notice&&<p role="status" className="notice">{notice}</p>}
   {overlay&&error.startsWith('Class saved, but')&&<button type="button" className="btn btnSecondary" onClick={()=>void refreshSavedClass()}>Refresh class data</button>}
   <div className="classesTabs" role="tablist" aria-label="Class sections">{tabs.filter(t=>t!=='Roster'||Boolean(draft.id&&canEdit)).map(t=><button type="button" role="tab" aria-selected={tab===t} key={t} onClick={()=>{if(t==='Roster'){if(dirty&&!confirm('Discard unsaved class changes before opening the roster?'))return;setDirty(false);setMode('view')}setTab(t)}}>{t}</button>)}</div>
   {error&&<p role="alert" className="notice">{error}</p>}
   {tab==='Roster'&&draft.id?<div role="tabpanel"><EnrolmentsPanel profileId={draft.id} canManage={canEdit&&draft.active&&published}/></div>:<form id="classes-edit-form" onSubmit={save}><fieldset disabled={busy||readOnly} className="classesFieldset"><div role="tabpanel">
    {tab==='Overview'&&<div className="classesForm"><label>Class name<input required value={draft.name} onChange={e=>patch({name:e.target.value})}/></label>
     <label>Category<select value={draft.category_id||''} onChange={e=>patch({category_id:e.target.value||null,programme_id:null})}><option value="">No category</option>{data?.categories.filter(c=>c.active||c.id===draft.category_id).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
     <label>Programme<select value={draft.programme_id||''} onChange={e=>{const p=data?.programmes.find(p=>p.id===e.target.value);patch({programme_id:p?.id||null,category_id:p?.category_id||draft.category_id})}}><option value="">No programme{draft.programme?` (legacy: ${draft.programme})`:''}</option>{data?.programmes.filter(p=>p.active||p.id===draft.programme_id).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
     <label>Visibility<select value={draft.visibility} onChange={e=>patch({visibility:e.target.value as Draft['visibility']})}><option value="internal">Internal</option><option value="public">Public</option></select></label><p className="muted">Public is a class label in Phase 1. It does not publish a public website or enable bookings.</p>
     <label>Class colour<input type="color" value={draft.session_colour} onChange={e=>patch({session_colour:e.target.value})}/></label>
     <label>Class description<textarea value={draft.description||''} onChange={e=>patch({description:e.target.value})}/></label></div>}
    {tab==='Schedule'&&<div className="classesForm">{published&&<p className="notice">Published schedule fields are protected. Use Change from date in the Class Library for future weekday, time, duration, venue or operating-date changes. Recurrence notes can be edited here. {!readOnly&&<button type="button" className="btn btnSecondary" onClick={()=>{if(dirty&&!confirm('Discard unsaved class changes?'))return;const profile=data?.profiles.find(p=>p.id===draft.id);if(profile){setDraft(null);setDirty(false);setLifecycle({profile,action:'change'})}}}>Change from date</button>}</p>}
     <label>Start date<input type="date" required={!published} disabled={published} value={draft.start_date||''} onChange={e=>patch({start_date:e.target.value||null})}/></label><label>End date (optional)<input type="date" disabled={published} min={draft.start_date||undefined} value={draft.end_date||''} onChange={e=>patch({end_date:e.target.value||null})}/></label>
     <label>Default session duration (minutes)<input type="number" min="1" max="1440" required disabled={published} value={draft.session_length_minutes} onChange={e=>patch({session_length_minutes:Number(e.target.value)})}/></label>
     {sessions.map((s,i)=><div className="classesSession" key={s.id||i}><label>Day<select disabled={published} value={s.weekday} onChange={e=>{setSessions(sessions.map((x,j)=>j===i?{...x,weekday:Number(e.target.value)}:x));request.current=null;setDirty(true)}}>{days.map((d,n)=><option key={d} value={n}>{d}</option>)}</select></label><label>Start time<input type="time" required disabled={published} value={s.start_time?.slice(0,5)||''} onChange={e=>{setSessions(sessions.map((x,j)=>j===i?{...x,start_time:e.target.value}:x));request.current=null;setDirty(true)}}/></label><label>Venue<select required disabled={published} value={s.venue_id} onChange={e=>{setSessions(sessions.map((x,j)=>j===i?{...x,venue_id:e.target.value}:x));request.current=null;setDirty(true)}}><option value="">Select venue</option>{data?.venues.filter(v=>v.active||v.id===s.venue_id).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Finish time<output>{published?s.finish_time?.slice(0,5):finishTime(s.start_time||'00:00',draft.session_length_minutes)}</output></label><label>Break (minutes)<input type="number" min="0" max={draft.session_length_minutes-1} disabled={published} value={s.break_minutes||0} onChange={e=>{setSessions(sessions.map((x,j)=>j===i?{...x,break_minutes:Number(e.target.value)}:x));request.current=null;setDirty(true)}}/></label><label>Recurrence notes<textarea value={s.notes||''} onChange={e=>{setSessions(sessions.map((x,j)=>j===i?{...x,notes:e.target.value}:x));request.current=null;setDirty(true)}}/></label>{!published&&sessions.length>1&&<button type="button" className="btn btnSecondary" onClick={()=>{setSessions(sessions.filter((_,j)=>j!==i));request.current=null;setDirty(true)}}>Remove recurrence</button>}</div>)}
     {!published&&<button type="button" className="btn btnSecondary" onClick={()=>{setSessions([...sessions,{venue_id:data?.venues.find(v=>v.active)?.id||'',weekday:1,start_time:'16:30',break_minutes:0}]);request.current=null;setDirty(true)}}>Add recurring session</button>}</div>}
    {tab==='Capacity and eligibility'&&<div className="classesForm"><label>Capacity<input required type="number" min="1" value={draft.capacity} onChange={e=>patch({capacity:Number(e.target.value)})}/></label><label>Minimum age<input type="number" min="0" value={draft.minimum_age??''} onChange={e=>patch({minimum_age:e.target.value===''?null:Number(e.target.value)})}/></label><label>Maximum age<input type="number" min={draft.minimum_age??0} value={draft.maximum_age??''} onChange={e=>patch({maximum_age:e.target.value===''?null:Number(e.target.value)})}/></label><label>Level / eligibility description<textarea value={draft.eligibility_description||''} onChange={e=>patch({eligibility_description:e.target.value})}/></label></div>}
    {tab==='Staffing'&&<div className="classesForm">
     {(['minimum_coaches','maximum_coaches','lead_coaches_required','assistant_coaches_required'] as const).map(key=><label key={key}>{({minimum_coaches:'Minimum coaches',maximum_coaches:'Maximum coaches',lead_coaches_required:'Lead coaches',assistant_coaches_required:'Assistant coaches'})[key]}<input type="number" required min="0" max="12" value={draft[key]??1} onChange={e=>patch({[key]:Number(e.target.value)})}/></label>)}
     {(['lead_recommended_qualification_id','assistant_recommended_qualification_id'] as const).map(key=><label key={key}>{key.startsWith('lead')?'Lead':'Assistant'} recommended qualification<select value={draft[key]||''} onChange={e=>patch({[key]:e.target.value||null})}><option value="">None</option>{data?.qualifications?.map(q=><option key={q.id} value={q.id}>{q.name}</option>)}</select></label>)}
     {(['warn_if_understaffed','critical_if_no_lead','allow_below_recommended_qualification'] as const).map(key=><label key={key}><input type="checkbox" checked={draft[key]??true} onChange={e=>patch({[key]:e.target.checked})}/>{({warn_if_understaffed:'Warn if understaffed',critical_if_no_lead:'Critical if no lead',allow_below_recommended_qualification:'Allow below recommended qualification'})[key]}</label>)}
     <p className="notice">Existing assignments remain unchanged and can only be edited through Staff Rota. Save added positions before selecting their published defaults. Future recurrence changes preserve existing staffing defaults. Payment preferences are saved for review; Load shifts continues to use its existing payment behaviour.</p>
     {sessions.map((s,i)=><div className="classesSession" key={s.id||i}><strong>{days[s.weekday||0]} · {s.start_time?.slice(0,5)}</strong>{Array.from({length:Math.min(12,Math.max(0,draft.lead_coaches_required+draft.assistant_coaches_required))},(_,n)=>{const slot=s.staffing?.find(x=>x.slot_number===n+1);return <div key={n}><strong>Position {n+1} · {n<draft.lead_coaches_required?'Lead':'Assistant'}</strong><label>Default coach<select disabled={published&&!data?.slots.some(x=>x.class_id===s.id&&x.slot_number===n+1)} value={slot?.default_profile_id||''} onChange={e=>updateSlot(i,n+1,{default_profile_id:e.target.value||null})}><option value="">Unassigned</option>{slot?.default_profile_id&&!data?.coaches?.some(c=>c.id===slot.default_profile_id)&&<option value={slot.default_profile_id}>{data?.slots.find(x=>x.class_id===s.id&&x.slot_number===n+1)?.coach_name||'Saved coach'} (currently unavailable)</option>}{data?.coaches?.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label><label>Payment preference<select disabled={published&&!data?.slots.some(x=>x.class_id===s.id&&x.slot_number===n+1)} value={slot?.payment_type||'standard'} onChange={e=>updateSlot(i,n+1,{payment_type:e.target.value as 'standard'|'enhanced'|'volunteer'})}>{['standard','enhanced','volunteer'].map(p=><option key={p} value={p}>{p[0].toUpperCase()+p.slice(1)}</option>)}</select></label></div>})}</div>)}
    </div>}
    {tab==='Activity'&&<div><p className="muted">Activity captured from Classes Phase 1. Earlier Master Timetable edits are not reconstructed.</p>{data?.activity.filter(a=>a.class_profile_id===draft.id).map((a,i)=><p key={i}>{new Date(a.created_at).toLocaleString('en-GB')} · {a.action}</p>)}</div>}
   </div><div className="classesSave">{!readOnly&&!published&&<button type="button" className="btn btnSecondary" disabled={!draft.id||dirty||busy||data?.lifecycle_version!==3} onClick={publish}>Publish to staffing</button>}</div>{!readOnly&&!published&&<p className="muted">Save first, then explicitly publish. Drafts stay out of Master Timetable and staffing generation.</p>}</fieldset></form>}
  </ClassConsole>}
  {taxonomy&&<ClassConsole title={`Manage ${taxonomy.kind}`} status="Club-defined configuration" onClose={()=>!busy&&setTaxonomy(null)}><form onSubmit={taxonomySave}><fieldset className="classesFieldset classesForm" disabled={busy}>{error&&<p role="alert">{error}</p>}<label>Name<input required value={taxonomy.data.name||''} onChange={e=>setTaxonomy({...taxonomy,data:{...taxonomy.data,name:e.target.value}})}/></label><label>Colour<input type="color" value={taxonomy.data.colour||'#6D3A91'} onChange={e=>setTaxonomy({...taxonomy,data:{...taxonomy.data,colour:e.target.value}})}/></label>{taxonomy.kind==='category'?<label>Display order<input type="number" value={taxonomy.data.display_order??0} onChange={e=>setTaxonomy({...taxonomy,data:{...taxonomy.data,display_order:Number(e.target.value)}})}/></label>:<><label>Category<select value={taxonomy.data.category_id||''} onChange={e=>setTaxonomy({...taxonomy,data:{...taxonomy.data,category_id:e.target.value||null}})}><option value="">No category</option>{data?.categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Description<textarea value={taxonomy.data.description||''} onChange={e=>setTaxonomy({...taxonomy,data:{...taxonomy.data,description:e.target.value}})}/></label></>}<label><input type="checkbox" checked={taxonomy.data.active!==false} onChange={e=>setTaxonomy({...taxonomy,data:{...taxonomy.data,active:e.target.checked}})}/> Active (uncheck to archive)</label><button type="submit" className="btn btnPrimary">Save {taxonomy.kind}</button></fieldset></form></ClassConsole>}
 </section>;
}
