'use client';
import {useEffect,useRef,useState} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import {classCommand,classDependencies} from '@/lib/classes/data';
import {addDays,today,type CalendarData,type ClassProfile,type Session} from '@/lib/classes/model';
import type {LifecycleAction} from './class-library';
import ClassConsole from './class-console';
const titles={end:'End class',archive:'Archive class',restore:'Restore class',delete:'Permanently delete class',change:'Change from date'};
export default function ClassLifecycle({client,profile,action,data,onClose,onSaved}:{client:SupabaseClient;profile:ClassProfile;action:LifecycleAction;data:CalendarData;onClose:()=>void;onSaved:()=>void}){
 const [date,setDate]=useState(addDays(today(),1)),[end,setEnd]=useState(profile.end_date||''),[name,setName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [check,setCheck]=useState<Awaited<ReturnType<typeof classDependencies>>|null>(null);
 const [sessions,setSessions]=useState<Partial<Session>[]>(()=>data.sessions.filter(s=>s.class_profile_id===profile.id&&s.active&&(!s.effective_to||s.effective_to>=addDays(today(),1))).map(s=>({...s,duration_minutes:s.duration_minutes||(((Number(s.finish_time.slice(0,2))*60+Number(s.finish_time.slice(3,5)))-(Number(s.start_time.slice(0,2))*60+Number(s.start_time.slice(3,5)))+1440)%1440)||1440})));
 const flight=useRef(false),request=useRef<string|null>(null);
 useEffect(()=>{let live=true;if(action==='delete')classDependencies(client,profile.id).then(v=>{if(live)setCheck(v)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[action,client,profile.id]);
 function patchSession(i:number,patch:Partial<Session>){request.current=null;setSessions(rows=>rows.map((s,j)=>i===j?{...s,...patch}:s))}
 async function submit(){if(flight.current)return;flight.current=true;setBusy(true);setError('');request.current??=crypto.randomUUID();try{await classCommand(client,action,profile.id,{final_date:date,effective_date:date,end_date:end||null,confirmation:name,sessions},request.current);onSaved()}catch(e){setError(e instanceof Error?e.message:'Unable to update class')}finally{flight.current=false;setBusy(false)}}
 return <ClassConsole title={`${titles[action]} · ${profile.name}`} status="Existing dated and payroll records are preserved" onClose={()=>!busy&&onClose()}><form onSubmit={e=>{e.preventDefault();void submit()}}><fieldset className="classesFieldset classesForm" disabled={busy}>
 {error&&<p role="alert" className="notice">{error}</p>}
 {action==='end'&&<><p>Choose the inclusive final operating date. Existing generated shifts remain unchanged, including any after this date.</p><label>Final operating date<input required type="date" min={profile.start_date||undefined} value={date} onChange={e=>{request.current=null;setDate(e.target.value)}}/></label></>}
 {action==='archive'&&<p>Archive the shared class and deactivate its weekly sessions and staffing positions. Historical records remain available. Repair archive also deactivates any recurrence left active by an older workflow.</p>}
 {action==='restore'&&<p>Restore only the sessions and positions captured when this class was archived. Retired versions and inactive positions stay retired. Existing operating dates still apply.</p>}
 {action==='delete'&&<><p>This permanently deletes an unused Draft. The server checks dependencies again when you confirm. Its activity is preserved in an independent audit record.</p>{!check&&!error&&<p role="status">Checking dependencies…</p>}{check&&!check.allowed&&<div role="alert"><p>{check.reason} End or Archive this class instead.</p><ul>{check.blockers.map((b,i)=><li key={i}>{b.table}: {b.count} linked references</li>)}</ul></div>}<label>Type the exact class name<input autoComplete="off" required value={name} onChange={e=>{request.current=null;setName(e.target.value)}}/></label></>}
 {action==='change'&&<><p>The existing schedule runs through the day before this date. Replacement weekly sessions start on this date. Choose a future date after any existing scheduled work or exclusions; the server rejects conflicts. This does not load shifts.</p><label>Change from date<input type="date" required min={addDays(today(),1)} value={date} onChange={e=>{request.current=null;setDate(e.target.value)}}/></label><label>New inclusive final date (optional)<input type="date" min={date} value={end} onChange={e=>{request.current=null;setEnd(e.target.value)}}/></label>{sessions.map((s,i)=><div key={i} className="classesSession"><label>Weekday<select value={s.weekday??1} onChange={e=>patchSession(i,{weekday:Number(e.target.value)})}>{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((d,n)=><option value={n} key={d}>{d}</option>)}</select></label><label>Start<input required type="time" value={s.start_time?.slice(0,5)||''} onChange={e=>patchSession(i,{start_time:e.target.value})}/></label><label>Duration (minutes)<input type="number" min="1" max="1440" required value={s.duration_minutes||60} onChange={e=>patchSession(i,{duration_minutes:Number(e.target.value)})}/></label><label>Venue<select required value={s.venue_id||''} onChange={e=>patchSession(i,{venue_id:e.target.value})}>{data.venues.filter(v=>v.active).map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label>Break<input type="number" min="0" max={(s.duration_minutes||60)-1} required value={s.break_minutes||0} onChange={e=>patchSession(i,{break_minutes:Number(e.target.value)})}/></label><label>Notes<textarea value={s.notes||''} onChange={e=>patchSession(i,{notes:e.target.value})}/></label>{sessions.length>1&&<button type="button" className="btn btnSecondary" onClick={()=>{request.current=null;setSessions(sessions.filter((_,j)=>i!==j))}}>Remove future session</button>}</div>)}<button type="button" className="btn btnSecondary" onClick={()=>{request.current=null;setSessions([...sessions,{weekday:1,start_time:'16:30',duration_minutes:60,venue_id:data.venues.find(v=>v.active)?.id,break_minutes:0}])}}>Add future session</button></>}
 <button className="btn btnPrimary" type="submit" disabled={busy||data.lifecycle_version!==3||(action==='delete'&&(!check?.allowed||name!==profile.name))}>{busy?'Saving…':titles[action]}</button>{data.lifecycle_version!==3&&<p>The reviewed Classes lifecycle upgrade must be installed before this action is available.</p>}
 </fieldset></form></ClassConsole>;
}
