'use client';
import {useMemo,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {updateAttendance} from '@/lib/registers/data';
import {attendanceCounts,attendanceLabel,attendanceStates,type AttendanceRow,type AttendanceState,type RegisterDetail} from '@/lib/registers/model';
import ClassConsole from './class-console';

type Pending={status:AttendanceState;arrival_time:string|null;note:string|null};
export default function RegisterConsole({initial,onClose}:{initial:RegisterDetail;onClose:()=>void}){
 const client=useMemo(()=>createClient(),[]),flight=useRef(new Set<string>()),requests=useRef(new Map<string,string>());
 const [rows,setRows]=useState(initial.athletes),[pending,setPending]=useState<Record<string,Pending>>({}),[saving,setSaving]=useState(new Set<string>()),[failed,setFailed]=useState<Record<string,string>>({}),[batching,setBatching]=useState(false),[confirming,setConfirming]=useState<string|null>(null);
 const counts=attendanceCounts(rows.map(row=>pending[row.id]?{...row,...pending[row.id]}:row));
 const effective=(row:AttendanceRow):Pending=>pending[row.id]||{status:row.status,arrival_time:row.arrival_time,note:row.note};
 function change(row:AttendanceRow,patch:Partial<Pending>){const next={...effective(row),...patch};if(next.status!=='late')next.arrival_time=null;setPending(value=>({...value,[row.id]:next}));setFailed(value=>{const copy={...value};delete copy[row.id];return copy});requests.current.delete(row.id)}
 async function save(row:AttendanceRow,override?:Pending,retainDraftOnFailure=true){const draft=override||pending[row.id];if(flight.current.has(row.id)||!draft)return true;flight.current.add(row.id);setSaving(value=>new Set(value).add(row.id));setFailed(value=>{const copy={...value};delete copy[row.id];return copy});try{if(!requests.current.has(row.id))requests.current.set(row.id,crypto.randomUUID());const saved=await updateAttendance(client,row.id,draft.status,draft.arrival_time,draft.note,requests.current.get(row.id)!);setRows(value=>value.map(item=>item.id===row.id?{...item,...saved}:item));setPending(value=>{const copy={...value};delete copy[row.id];return copy});requests.current.delete(row.id);return true}catch(error){if(retainDraftOnFailure)setPending(value=>({...value,[row.id]:draft}));else setPending(value=>{const copy={...value};delete copy[row.id];return copy});setFailed(value=>({...value,[row.id]:error instanceof Error?error.message:'Save failed'}));return false}finally{flight.current.delete(row.id);setSaving(value=>{const next=new Set(value);next.delete(row.id);return next})}}
 function quickStatus(row:AttendanceRow,status:AttendanceState){const current=effective(row),draft={...current,status,arrival_time:status==='late'?current.arrival_time:null};setPending(value=>({...value,[row.id]:draft}));requests.current.delete(row.id);void save(row,draft)}
 async function markAll(){if(batching)return;setBatching(true);const targets=rows.filter(row=>row.status==='unmarked');for(const row of targets)change(row,{status:'present',arrival_time:null});await Promise.resolve();const results=await Promise.allSettled(targets.map(async row=>{const draft:Pending={status:'present',arrival_time:null,note:effective(row).note};setPending(value=>({...value,[row.id]:draft}));const requestId=crypto.randomUUID();requests.current.set(row.id,requestId);flight.current.add(row.id);setSaving(value=>new Set(value).add(row.id));try{const saved=await updateAttendance(client,row.id,'present',null,draft.note,requestId);setRows(value=>value.map(item=>item.id===row.id?{...item,...saved}:item));setPending(value=>{const copy={...value};delete copy[row.id];return copy});setFailed(value=>{const copy={...value};delete copy[row.id];return copy});requests.current.delete(row.id)}catch(error){setFailed(value=>({...value,[row.id]:error instanceof Error?error.message:'Save failed'}));throw error}finally{flight.current.delete(row.id);setSaving(value=>{const next=new Set(value);next.delete(row.id);return next})}}));setBatching(false);return results}
 function askClear(row:AttendanceRow){if(row.status==='unmarked'||saving.has(row.id))return;setConfirming(row.id)}
 async function clearMark(row:AttendanceRow){if(row.status==='unmarked'||flight.current.has(row.id))return;setConfirming(null);requests.current.delete(row.id);await save(row,{status:'unmarked',arrival_time:null,note:null},false)}
 async function retryFailed(){await Promise.allSettled(rows.filter(row=>failed[row.id]).map(row=>save(row)))}
 const dirty=Object.keys(pending).length;
 return <ClassConsole title={initial.occurrence.class_name} status={`${initial.occurrence.occurrence_date} · ${initial.occurrence.start_time.slice(0,5)}–${initial.occurrence.finish_time.slice(0,5)} · ${initial.occurrence.venue_name}`} onClose={onClose} footer={<><span className="registerSaveSummary" role="status">{saving.size?'Saving…':Object.keys(failed).length?`${Object.keys(failed).length} failed`:dirty?`${dirty} unsaved`:counts.completed?'Register complete':'Register incomplete'}</span>{Object.keys(failed).length>0&&<button className="btn btnSecondary" type="button" onClick={()=>void retryFailed()}>Retry failed only</button>}<button className="btn btnSecondary" type="button" onClick={onClose}>Back to Registers</button></>}>
  <div className="registerToolbar"><div><strong>{counts.marked} / {counts.expected} marked</strong><span>{counts.completed?'Complete':'Incomplete'}</span></div><button className="btn btnPrimary" type="button" disabled={batching||saving.size>0||rows.length===0} onClick={()=>void markAll()}>{batching?'Marking…':'Mark all present'}</button></div>
  {!rows.length?<div className="registerEmpty"><h3>No expected athletes</h3><p>No effective Active or Trial enrolments select this weekly recurrence on this date.</p></div>:<div className="registerAthletes">{rows.map(row=>{const value=effective(row),isSaving=saving.has(row.id),isConfirming=confirming===row.id;return <article key={row.id} className={`registerAthlete ${pending[row.id]?'isDirty':''} ${failed[row.id]?'hasError':''}`}><header><div><h3>{row.athlete_name}</h3>{row.is_trial&&<span className="registerTrial">Trial</span>}</div><span className="registerRowState">{failed[row.id]?'Failed':isSaving?'Saving':pending[row.id]?'Unsaved':'Saved'}</span></header><div className="registerStateButtons" aria-label={`Attendance for ${row.athlete_name}`}>{attendanceStates.filter(state=>state!=='unmarked').map(state=><button type="button" key={state} aria-pressed={value.status===state} disabled={isSaving} onClick={()=>quickStatus(row,state)}>{attendanceLabel(state)}</button>)}</div>{value.status==='late'&&<label>Arrival time<input type="time" value={value.arrival_time?.slice(0,5)||''} onChange={event=>change(row,{arrival_time:event.target.value||null})}/></label>}<label>Internal note<textarea maxLength={1000} rows={2} value={value.note||''} onChange={event=>change(row,{note:event.target.value})}/></label>{value.status!=='unmarked'&&!isConfirming&&<button type="button" className="btn btnSecondary registerClear" disabled={isSaving} onClick={()=>askClear(row)}>Clear mark</button>}{isConfirming&&<div className="registerClearConfirm" role="alertdialog" aria-label={`Return ${row.athlete_name} to Unmarked?`}><strong>Return {row.athlete_name} to Unmarked?</strong><div><button type="button" className="btn btnSecondary" disabled={isSaving} onClick={()=>setConfirming(null)}>Cancel</button><button type="button" className="btn btnPrimary" disabled={isSaving} onClick={()=>void clearMark(row)}>{isSaving?'Clearing…':'Confirm clear'}</button></div></div>}{failed[row.id]&&<p role="alert" className="registerError">{failed[row.id]}</p>}<button type="button" className="btn btnSecondary registerSave" disabled={!pending[row.id]||isSaving} onClick={()=>void save(row)}>{isSaving?'Saving…':failed[row.id]?'Retry save':'Save note / arrival'}</button></article>})}</div>}
 </ClassConsole>
}
