'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {CalendarIcon} from '@/components/icons';
import {createClient} from '@/lib/supabase/client';
import {loadRegisters,openRegister} from '@/lib/registers/data';
import {addDays,today} from '@/lib/classes/model';
import {emptyRegisterFilters,filterRegisters,type RegisterDetail,type RegisterFilters,type RegisterSummary} from '@/lib/registers/model';
import RegisterConsole from './register-console';
import ClassesDateControls from './classes-date-controls';

export default function RegistersPanel({initialProfileId}:{initialProfileId?:string|null}){
 const client=useMemo(()=>createClient(),[]),[date,setDate]=useState(today),[rows,setRows]=useState<RegisterSummary[]|null>(null),[filters,setFilters]=useState<RegisterFilters>(emptyRegisterFilters),[error,setError]=useState(''),[loading,setLoading]=useState(true),[detail,setDetail]=useState<RegisterDetail|null>(null),[opening,setOpening]=useState(''),[revision,setRevision]=useState(0),sequence=useRef(0);
 useEffect(()=>{const id=++sequence.current;setLoading(true);setError('');loadRegisters(client,date).then(value=>{if(id===sequence.current)setRows(value)}).catch(e=>{if(id===sequence.current)setError(e.message)}).finally(()=>{if(id===sequence.current)setLoading(false)});return()=>{sequence.current++}},[client,date,revision]);
 const visible=filterRegisters((rows||[]).filter(row=>!initialProfileId||row.class_profile_id===initialProfileId),filters),values=rows||[],completeCount=visible.filter(row=>row.completed).length;
 async function open(row:RegisterSummary){if(opening)return;setOpening(row.class_id);setError('');try{setDetail(await openRegister(client,row.class_id,date,crypto.randomUUID()))}catch(e){setError(e instanceof Error?e.message:'Register could not be opened.')}finally{setOpening('')}}
 const status=(row:RegisterSummary)=>row.expected_count===0?'No enrolled athletes':row.completed?'Complete':row.marked_count===0?'Not started':'In progress';
 return <section className="registersPanel" aria-labelledby="registers-heading"><header className="classesHeader registersHeader"><div className="classesHeroIdentity"><span className="classesHeroIcon" aria-hidden="true"><CalendarIcon/></span><div><span className="classesEyebrow">ATTENDANCE</span><h1 id="registers-heading">Registers</h1><p>Take and review attendance for your scheduled classes.</p></div></div></header>
  <section className="registersToolbar" aria-label="Register filters"><ClassesDateControls date={date} onPrevious={()=>setDate(addDays(date,-1))} onToday={()=>setDate(today())} onNext={()=>setDate(addDays(date,1))} onChange={setDate}/>
  <div className="registerFilters"><label>Venue<select value={filters.venue} onChange={e=>setFilters({...filters,venue:e.target.value})}><option value="">All venues</option>{[...new Map(values.map(row=>[row.venue_id,row.venue_name])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Category<select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">All categories</option>{[...new Map(values.filter(row=>row.category_id).map(row=>[row.category_id!,row.category_name||'Category'])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Programme<select value={filters.programme} onChange={e=>setFilters({...filters,programme:e.target.value})}><option value="">All programmes</option>{[...new Map(values.filter(row=>row.programme_id).map(row=>[row.programme_id!,row.programme_name||'Programme'])).entries()].map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Completion<select value={filters.completion} onChange={e=>setFilters({...filters,completion:e.target.value})}><option value="">All registers</option><option value="complete">Complete</option><option value="incomplete">Incomplete</option></select></label></div>
  {!loading&&!error&&<p className="registerSummary" aria-live="polite">{visible.length} {visible.length===1?'class':'classes'} · {completeCount} complete · {visible.length-completeCount} to take</p>}</section>
  {error&&<div className="registerEmpty" role="alert"><h3>Registers could not be loaded</h3><p>{error}</p><button className="btn btnSecondary" onClick={()=>setRevision(value=>value+1)}>Try again</button></div>}{loading?<p className="registerEmpty" role="status">Loading registers…</p>:!error&&!visible.length?<div className="registerEmpty"><h3>No classes for this date</h3><p>No available classes match the selected date and filters.</p></div>:!error&&<div className="registerCards">{visible.sort((a,b)=>a.start_time.localeCompare(b.start_time)).map(row=><article key={row.class_id}><div className="registerCardTime"><strong>{row.start_time.slice(0,5)}</strong><span>{row.finish_time.slice(0,5)}</span></div><div className="registerCardContent"><div className="registerCardHeading"><h2>{row.class_name}</h2><span className={`registerStatus registerStatus-${status(row).toLowerCase().replaceAll(' ','-')}`}>{status(row)}</span></div><p>{[row.venue_name,row.category_name,row.programme_name].filter(Boolean).join(' · ')}</p>{row.expected_count>0&&<span>{row.marked_count} of {row.expected_count} marked</span>}</div><button className="btn btnSecondary" disabled={opening===row.class_id} onClick={()=>void open(row)}>{opening===row.class_id?'Opening…':'Open register'}</button></article>)}</div>}
  {detail&&<RegisterConsole initial={detail} onClose={()=>{setDetail(null);setRevision(value=>value+1)}}/>}
 </section>
}
