"use client";
import {useState} from 'react';
import { ageAt,journeyLabel,type Family,type Athlete,type Contact,type Stamp } from '@/lib/members/model';
import MemberEssentials from './member-essentials';
import EnrolmentsPanel from '@/components/enrolments/enrolments-panel';
import RecentAttendance from './recent-attendance';
import type { EditorSpec } from './member-editor';
export default function MemberDetail({family,athleteId,onFamily,onAthlete,onEdit,onStatus,onBack,busy,canDelete,onDelete,onSaved}:{family:Family;athleteId:string|null;onFamily:()=>void;onAthlete:(id:string)=>void;onEdit:(spec:EditorSpec)=>void;onStatus:(entity:'family'|'contact'|'athlete',record:Stamp)=>void;onBack:()=>void;busy:boolean;onSaved?:()=>void;canDelete:boolean;onDelete:(id:string|null)=>void}){
 const [tab,setTab]=useState('overview');
 const athlete=family.athletes.find(a=>a.id===athleteId);
 const primary=family.contacts.find(c=>c.id===family.primary_contact_id);
 const contactCard=(contact:Contact)=>{const links=family.relationships.filter(link=>link.contact_id===contact.id&&link.status==='active');return <article key={contact.id}><div><h3>{contact.display_name}</h3><span className="membersStatus">Portal: {journeyLabel(contact.portal_status||'not_invited')}</span><p>{contact.email||'No email'} · {contact.phone||'No mobile number'}</p><p>{contact.status==='archived'?'Archived contact':family.primary_contact_id===contact.id?'Primary family contact':'Contact'}</p>{links.map(link=><p key={link.athlete_id}>{family.athletes.find(a=>a.id===link.athlete_id)?.display_name||'Connected athlete'} · {journeyLabel(link.relationship)}{link.is_primary?' · Primary':''}{link.is_emergency?' · Emergency':''}</p>)}</div><div className="memberActions"><button className="btn btnSecondary" disabled={busy||contact.status==='archived'} onClick={()=>onEdit({kind:'contact',family,record:contact})}>Edit contact</button><button className="btn btnSecondary" disabled={busy} onClick={()=>onStatus('contact',contact)}>{contact.status==='active'?'Archive contact':'Reactivate contact'}</button></div></article>};
 const athleteCard=(a:Athlete)=><article key={a.id}><div><h3>{a.display_name}</h3><p>{journeyLabel(a.journey_status)} · {a.date_of_birth?`${ageAt(a.date_of_birth)} years old`:'Date of birth not recorded'} · {journeyLabel(a.status)}</p></div><button className="btn btnSecondary" onClick={()=>onAthlete(a.id)}>View athlete</button></article>;
 return <div className="memberDetail">{athlete&&<div className="memberActions"><button className="btn btnSecondary" onClick={onFamily}>← Family overview</button></div>}{athlete?<>
 <header className="membersHeader"><div><span className="membersEyebrow">Athlete</span><h2>{athlete.display_name}</h2><p>{family.display_name} · {athlete.date_of_birth?`${ageAt(athlete.date_of_birth)} years old`:"Age not recorded"}</p><span className="membersStatus">{journeyLabel(athlete.journey_status)}</span></div><div className="memberActions"><button className="btn btnSecondary" disabled={busy} onClick={()=>onEdit({kind:'athlete',family,record:athlete})}>Edit athlete</button><button className="btn btnSecondary" disabled={busy} onClick={()=>onStatus('athlete',athlete)}>{athlete.status==='active'?'Archive athlete':'Reactivate athlete'}</button></div></header>
 <section className="card memberDetailSection"><h3>Personal details</h3><dl><dt>Date of birth</dt><dd>{athlete.date_of_birth||'Not recorded'}</dd><dt>Age</dt><dd>{athlete.date_of_birth?ageAt(athlete.date_of_birth):'Not recorded'}</dd><dt>Gender</dt><dd>{athlete.gender||'Not specified'}</dd><dt>Membership journey</dt><dd>{journeyLabel(athlete.journey_status)}</dd><dt>Record state</dt><dd>{journeyLabel(athlete.status)}</dd></dl></section>
 <section className="card memberDetailSection"><h3>Connected contacts</h3><div className="membersRecords">{family.contacts.filter(c=>family.relationships.some(r=>r.athlete_id===athlete.id&&r.contact_id===c.id&&r.status==='active')).map(contactCard)}</div>{!family.relationships.some(r=>r.athlete_id===athlete.id&&r.status==='active')&&<p>No contacts connected yet. Open the family and edit a contact to connect this athlete.</p>}</section>
 <section className="card memberDetailSection"><EnrolmentsPanel athlete={{id:athlete.id,display_name:athlete.display_name}} canManage={athlete.status==='active'&&family.status==='active'}/></section>
 <RecentAttendance athleteId={athlete.id}/>
 </>:<>
 <header className="membersHeader"><span className="membersStatus" data-status={family.status}>{journeyLabel(family.status)}</span><div className="memberActions"><button className="btn btnSecondary" disabled={busy} onClick={()=>onEdit({kind:'family',family})}>Edit family</button><button className="btn btnSecondary" disabled={busy} onClick={()=>onStatus('family',family)}>{family.status==='active'?'Archive family':'Reactivate family'}</button></div></header>
 <div className="membersCounts"><div><span>Connected athletes</span><strong>{family.athletes.length}</strong></div><div><span>Trusted contacts</span><strong>{family.contacts.length}</strong></div></div>
 <nav className="membersTabs" aria-label="Family sections">{['overview','contacts','athletes','activity'].map(t=><button key={t} className={tab===t?'selected':''} aria-current={tab===t?'page':undefined} onClick={()=>setTab(t)}>{journeyLabel(t)}</button>)}</nav>
 {tab==='overview'&&<section className="card memberDetailSection"><h3>Account summary</h3><dl><dt>Account status</dt><dd>{journeyLabel(family.status)}</dd><dt>Primary contact</dt><dd>{primary?.display_name||'Not selected'}</dd><dt>Athletes</dt><dd>{family.athletes.length}</dd><dt>Journeys</dt><dd>{Array.from(new Set(family.athletes.map(a=>journeyLabel(a.journey_status)))).join(', ')||'None yet'}</dd><dt>Portal</dt><dd>{primary?journeyLabel(primary.portal_status||'not_invited'):'No primary contact'}</dd><dt>Last updated</dt><dd>{new Date(family.updated_at).toLocaleString()}</dd></dl><p>{primary?`${primary.email||'No email'} · ${primary.phone||'No mobile number'}`:'Add or edit a contact to choose the primary family contact.'}</p></section>}

 {tab==='contacts'&&<section className="card memberDetailSection"><div className="membersHeader"><h3>Contacts</h3><button className="btn btnPrimary" disabled={busy} onClick={()=>onEdit({kind:'contact',family})}>Add contact</button></div><div className="membersRecords">{family.contacts.map(contactCard)}</div>{!family.contacts.length&&<p>No contacts yet.</p>}</section>}
 {tab==='athletes'&&<section className="card memberDetailSection"><div className="membersHeader"><h3>Athletes</h3><button className="btn btnPrimary" disabled={busy} onClick={()=>onEdit({kind:'athlete',family})}>Add athlete</button></div><div className="membersRecords">{family.athletes.map(athleteCard)}</div>{!family.athletes.length&&<p>No athletes yet. Add an athlete to keep their journey connected to this family.</p>}</section>}
 </>}{onSaved&&<MemberEssentials family={family} athleteId={athlete?.id||null} onSaved={onSaved} section={athlete?'athlete':tab}/>} {canDelete&&(athlete||tab==='overview')&&<section className="memberDangerZone"><span className="membersEyebrow">Danger zone</span><h3>Permanent deletion</h3><p>Archive is the recommended option. Permanent deletion removes this {athlete?'athlete':'family'} and cannot be undone.</p><button className="btn memberDangerButton" disabled={busy} onClick={()=>onDelete(athlete?.id||null)}>Permanently delete {athlete?'athlete':'family'}</button></section>}</div>;
}
