"use client";
import {useMemberDialog} from './use-member-dialog';
import { useRef,useState } from 'react';
import { athleteError,contactError,creationError,journeys,journeyLabel,newAthlete,newContact,type Athlete,type AthleteDraft,type Contact,type ContactDraft,type Family,type FamilyDraft } from '@/lib/members/model';
import type { MemberCommand,WriteResult } from '@/lib/members/management';
export type EditorSpec={kind:'create'|'family'|'contact'|'athlete';family?:Family;record?:Contact|Athlete};
function names(record?:{first_name:string;last_name:string;display_name:string}){return {first_name:record?.first_name||record?.display_name.split(' ')[0]||'',last_name:record?.last_name||record?.display_name.split(' ').slice(1).join(' ')||''}}
export default function MemberEditor({spec,onSave,onClose,onSaved}:{spec:EditorSpec;onSave:(command:MemberCommand,ack:boolean)=>Promise<WriteResult>;onClose:()=>void;onSaved:(id:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);
 const [step,setStep]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(''),[warnings,setWarnings]=useState<string[]>([]),[ack,setAck]=useState(false);
 const [family,setFamily]=useState<FamilyDraft>({display_name:spec.family?.display_name||'',status:spec.family?.status||'active'});
 const [contact,setContact]=useState<ContactDraft>(()=>{
  const r=spec.kind==='contact'?spec.record as Contact:undefined,links=spec.family?.relationships.filter(link=>link.contact_id===r?.id&&link.status==='active')||[];
  return {...newContact(),...names(r),email:r?.email||'',phone:r?.phone||'',relationship:links[0]?.relationship||'parent',is_primary:r?spec.family?.primary_contact_id===r.id:spec.kind==='create',is_emergency:r?links.some(l=>l.is_emergency):true,athlete_ids:r?links.map(l=>l.athlete_id):spec.family?.athletes.filter(a=>a.status==='active').map(a=>a.id)||[]};
 });
 const [athletes,setAthletes]=useState<AthleteDraft[]>(()=>{const r=spec.kind==='athlete'?spec.record as Athlete:undefined;return [{...newAthlete(),...names(r),date_of_birth:r?.date_of_birth||'',gender:r?.gender||'',journey_status:r?.journey_status||'enquiry'}]});
 useMemberDialog(dialog);
 function changed(){setWarnings([]);setAck(false);setError('')}
 function setC(next:ContactDraft){changed();setContact(next)}
 function setA(index:number,next:AthleteDraft){changed();setAthletes(current=>current.map((a,i)=>i===index?next:a))}
 const familyFields=<div className="memberFormFields"><label>Family display name<input maxLength={200} value={family.display_name} onChange={e=>{changed();setFamily({...family,display_name:e.target.value})}}/></label><label>Account status<select value={family.status} onChange={e=>{changed();setFamily({...family,status:e.target.value as FamilyDraft['status']})}}><option value="active">Active</option><option value="archived">Archived</option></select></label></div>;
 const contactFields=<div className="memberFormFields"><div className="memberFormPair"><label>First name<input maxLength={90} value={contact.first_name} onChange={e=>setC({...contact,first_name:e.target.value})}/></label><label>Last name<input maxLength={90} value={contact.last_name} onChange={e=>setC({...contact,last_name:e.target.value})}/></label></div><label>Relationship to selected athletes<select value={contact.relationship} onChange={e=>setC({...contact,relationship:e.target.value})}>{['parent','guardian','self','other'].map(value=><option key={value} value={value}>{journeyLabel(value)}</option>)}</select></label><label>Email<input type="email" maxLength={254} value={contact.email} onChange={e=>setC({...contact,email:e.target.value})}/></label><label>Mobile number<input type="tel" maxLength={40} value={contact.phone} onChange={e=>setC({...contact,phone:e.target.value})}/></label><label className="memberCheck"><input type="checkbox" checked={contact.is_primary} onChange={e=>setC({...contact,is_primary:e.target.checked})}/>Primary family contact and primary for selected athletes</label><label className="memberCheck"><input type="checkbox" checked={contact.is_emergency} onChange={e=>setC({...contact,is_emergency:e.target.checked})}/>Emergency contact for selected athletes</label>{spec.family&&<fieldset><legend>Connected athletes</legend><p>Relationship and contact settings apply to each selected athlete.</p>{spec.family.athletes.map(a=><label className="memberCheck" key={a.id}><input type="checkbox" checked={contact.athlete_ids.includes(a.id)} onChange={e=>setC({...contact,athlete_ids:e.target.checked?[...contact.athlete_ids,a.id]:contact.athlete_ids.filter(id=>id!==a.id)})}/>{a.display_name}{a.status==='archived'?' (archived)':''}</label>)}</fieldset>}</div>;
 const athleteFields=<div className="memberFormFields">{athletes.map((a,index)=><fieldset key={index}><legend>{spec.kind==='create'?`Athlete ${index+1}`:'Athlete details'}</legend><div className="memberFormPair"><label>First name<input maxLength={90} value={a.first_name} onChange={e=>setA(index,{...a,first_name:e.target.value})}/></label><label>Last name<input maxLength={90} value={a.last_name} onChange={e=>setA(index,{...a,last_name:e.target.value})}/></label></div><label>Date of birth<input type="date" min="1900-01-01" max={new Date().toISOString().slice(0,10)} value={a.date_of_birth} onChange={e=>setA(index,{...a,date_of_birth:e.target.value})}/></label><label>Gender (optional)<input maxLength={80} value={a.gender} onChange={e=>setA(index,{...a,gender:e.target.value})}/></label><label>Membership journey<select value={a.journey_status} onChange={e=>setA(index,{...a,journey_status:e.target.value as AthleteDraft['journey_status']})}>{journeys.map(value=><option key={value} value={value}>{journeyLabel(value)}</option>)}</select></label>{athletes.length>1&&<button type="button" className="btn btnSecondary" onClick={()=>{changed();setAthletes(athletes.filter((_,i)=>i!==index))}}>Remove athlete {index+1}</button>}</fieldset>)}{spec.kind==='create'&&athletes.length<20&&<button type="button" className="btn btnSecondary" onClick={()=>{changed();setAthletes([...athletes,newAthlete()])}}>Add another athlete</button>}{spec.kind==='athlete'&&!spec.record&&<p>After adding, use Edit contact to connect this athlete to their guardians or adult contact.</p>}</div>;
 function advance(){const validation=step===1?(!family.display_name.trim()?'Enter a family name.':''):step===2?contactError(contact):athletes.map(athleteError).find(Boolean)||'';if(validation){setError(validation);return}setError('');setStep(step+1)}
 async function save(){
  const validation=spec.kind==='create'?creationError(family,contact,athletes):spec.kind==='family'?(!family.display_name.trim()?'Enter a family name.':''):spec.kind==='contact'?contactError(contact):athleteError(athletes[0]);
  if(validation){setError(validation);return}
  const command:MemberCommand={action:spec.kind==='create'?'create_family':spec.kind==='family'?'save_family':spec.kind==='contact'?'save_contact':'save_athlete',familyId:spec.family?.id,recordId:spec.kind==='family'?spec.family?.id:spec.record?.id,updatedAt:spec.kind==='family'?spec.family?.updated_at:spec.record?.updated_at,data:spec.kind==='create'?{family,contact,athletes}:spec.kind==='family'?family:spec.kind==='contact'?contact:athletes[0]};
  setBusy(true);setError('');try{const result=await onSave(command,ack);if(result.requires_confirmation){setWarnings(result.warnings||[]);setAck(false)}else if(result.family_id)onSaved(result.family_id)}catch(e){setError(e instanceof Error?e.message:'Could not save')}finally{setBusy(false)}
 }
 return <dialog ref={dialog} className={`memberEditor memberScheduleForm ${spec.kind==='create'?'memberWizard':''}`} aria-labelledby="member-editor-title" onCancel={e=>{e.preventDefault();if(!busy)onClose()}}><div className="v311AdminShiftHero"><div><span>{spec.kind==='create'?`Step ${step} of 4 · ${['Family','Primary contact','Athletes','Review and create'][step-1]}`:'Member management'}</span><h2 id="member-editor-title">{spec.kind==='create'?'Add family':`${spec.record||spec.kind==='family'?'Edit':'Add'} ${spec.kind}`}</h2></div><button className="iconButton" aria-label="Close member form" disabled={busy} onClick={onClose}>×</button></div>{spec.kind==='create'&&<ol className="memberSteps" aria-label="Creation steps">{['Family','Contact','Athletes','Review'].map((label,i)=><li key={label} aria-current={step===i+1?'step':undefined} className={step>=i+1?'reached':''}><span>{i+1}</span>{label}</li>)}</ol>}<fieldset className="memberEditorBody" disabled={busy}>{spec.kind==='create'?(step===1?familyFields:step===2?contactFields:step===3?athleteFields:<div className="memberReview"><h3>{family.display_name}</h3><p>Account: {journeyLabel(family.status)}</p><h4>Primary contact</h4><p>{contact.first_name} {contact.last_name} · {journeyLabel(contact.relationship)}</p><p>{contact.email||'No email'} · {contact.phone||'No mobile number'}</p><p>{contact.is_primary?'Primary contact':'Not marked primary'} · {contact.is_emergency?'Emergency contact':'Not marked emergency'}</p><h4>Athletes</h4>{athletes.map((a,i)=><p key={i}><strong>{a.first_name} {a.last_name}</strong><br/>{a.date_of_birth} · {a.gender||'Gender not specified'} · {journeyLabel(a.journey_status)}</p>)}<p>The family, contact and all athletes will be created together.</p></div>):spec.kind==='family'?familyFields:spec.kind==='contact'?contactFields:athleteFields}
 {error&&<div className="notice danger" role="alert">{error}<button type="button" className="btn btnSecondary" onClick={()=>setError('')}>Dismiss error</button></div>}{warnings.length>0&&<div className="notice" role="alert"><strong>Possible duplicates in this club</strong><ul>{warnings.map((warning,i)=><li key={i}>{warning}</li>)}</ul><label className="memberCheck"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>I have reviewed these warnings and want to continue.</label></div>}</fieldset><footer><button className="btn btnSecondary" disabled={busy} onClick={onClose}>Cancel</button>{spec.kind==='create'&&step>1&&<button className="btn btnSecondary" disabled={busy} onClick={()=>{changed();setStep(step-1)}}>Back</button>}{spec.kind==='create'&&step<4?<button className="btn btnPrimary" onClick={advance}>Continue</button>:<button className="btn btnPrimary" disabled={busy||(warnings.length>0&&!ack)} onClick={()=>void save()}>{busy?'Saving…':spec.kind==='create'?'Create family':'Save changes'}</button>}</footer></dialog>;
}
