"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import type {Family} from '@/lib/members/model';
type Details={address:string;updated_at:string;contacts:{id:string;updated_at:string;preferences:Record<string,boolean|null>;portal_status:string}[];athletes:{id:string;updated_at:string;medical_notes:string;allergies:string}[];notes:{id:string;athlete_id:string|null;body:string;created_at:string}[];activity:{entity:string;action:string;created_at:string}[]};
export default function MemberEssentials({family,athleteId,onSaved,section='overview'}:{family:Family;athleteId:string|null;onSaved:()=>void;section?:string}){
 const client=useMemo(()=>createClient(),[]),pending=useRef(false);const [data,setData]=useState<Details|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{let cancelled=false;setData(null);setError('');void client.rpc('member_essentials',{p_family_id:family.id}).then(({data,error})=>{if(cancelled)return;if(error)setError('Additional member details could not be loaded. Check the Members finishing migration.');else setData(data as Details)});return()=>{cancelled=true}},[client,family.id,family.updated_at,revision]);
 async function save(action:string,record:string|null,values:unknown,stamp?:string){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{const {error}=await client.rpc('member_essentials',{p_family_id:family.id,p_action:action,p_record_id:record,p_data:values,p_stamp:stamp||null});if(error)throw new Error(error.code==='40001'?'These details changed. Reload before saving.':'Details could not be saved. Check your access and entered information.');setNote('');onSaved();setRevision(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Could not save details.')}finally{pending.current=false;setBusy(false)}}
 const medical=data?.athletes.find(a=>a.id===athleteId);
 return <section hidden={!athleteId&&section==='athletes'} className="card memberDetailSection"><h3>{athleteId?'Health & internal notes':section==='activity'?'Activity & internal notes':section==='contacts'?'Preferences & portal access':'Address'}</h3>
 {error&&<div className="notice danger" role="alert">{error}<div className="memberActions"><button className="btn btnSecondary" onClick={()=>setError('')}>Dismiss error</button><button className="btn btnSecondary" onClick={()=>setRevision(v=>v+1)}>Reload details</button></div></div>}
 {!data&&!error&&<p role="status">Loading details…</p>}{data&&<>
 {!athleteId&&<>{section==='overview'&&<form className="memberFormFields" onSubmit={e=>{e.preventDefault();void save('address',null,{address:data.address},data.updated_at)}}><label>Family address<textarea maxLength={1000} rows={3} value={data.address} onChange={e=>setData({...data,address:e.target.value})}/></label><button className="btn btnSecondary" disabled={busy}>Save address</button></form>}
 {section==='contacts'&&<><h4>Contact preferences & portal access</h4><div className="membersRecords">{data.contacts.map(c=><article key={c.id}><form className="memberFormFields" onSubmit={e=>{e.preventDefault();void save('preferences',c.id,c.preferences,c.updated_at)}}><strong>{family.contacts.find(x=>x.id===c.id)?.display_name}</strong><span className="membersStatus">Portal: {({not_invited:'Not invited',invited:'Invited',active:'Active',disabled:'Disabled'} as Record<string,string>)[c.portal_status]||'Not invited'}</span>{(['email','sms','marketing'] as const).map(k=><label key={k}>{k==='sms'?'SMS':k==='email'?'Email':'Marketing'} preference<select value={c.preferences[k]===true?'yes':c.preferences[k]===false?'no':'unknown'} onChange={e=>setData({...data,contacts:data.contacts.map(x=>x.id===c.id?{...x,preferences:{...x.preferences,[k]:e.target.value==='unknown'?null:e.target.value==='yes'}}:x)})}><option value="unknown">Not recorded</option><option value="yes">Yes</option><option value="no">No</option></select></label>)}<button className="btn btnSecondary" disabled={busy}>Save preferences</button></form></article>)}</div><p>Portal access is read-only. Invitations and customer login are not available yet.</p></>}</>}
 {medical&&<form className="memberFormFields" onSubmit={e=>{e.preventDefault();void save('medical',medical.id,{medical_notes:medical.medical_notes,allergies:medical.allergies},medical.updated_at)}}><p>Restricted to authorised club users. These details are never copied into the activity history.</p>{(['medical_notes','allergies'] as const).map(k=><label key={k}>{k==='allergies'?'Allergies':'Essential medical notes'}<textarea maxLength={4000} rows={3} value={medical[k]} onChange={e=>setData({...data,athletes:data.athletes.map(a=>a.id===medical.id?{...a,[k]:e.target.value}:a)})}/></label>)}<button className="btn btnSecondary" disabled={busy}>Save health details</button></form>}
 {(athleteId||section==='activity')&&<><h4>Dated internal notes</h4><p>Notes are retained and prevent permanent deletion. Archive records when their history must be kept.</p><form className="memberFormFields" onSubmit={e=>{e.preventDefault();void save('note',athleteId,{body:note})}}><label>New internal note<textarea maxLength={4000} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><button className="btn btnSecondary" disabled={busy||!note.trim()}>Add dated note</button></form>
 {data.notes.filter(n=>n.athlete_id===athleteId).map(n=><article key={n.id}><time>{new Date(n.created_at).toLocaleString()}</time><p style={{whiteSpace:'pre-wrap'}}>{n.body}</p></article>)}</>}
 {!athleteId&&section==='activity'&&<><h4>Family activity · latest 50 events</h4>{data.activity.length?data.activity.map((event,i)=><p key={i}><time>{new Date(event.created_at).toLocaleString()}</time> · {event.entity} {event.action}</p>):<p>No activity recorded since this release.</p>}</>}
 </>}</section>;
}
