"use client";
import { useEffect,useMemo,useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { deleteMember,manageMember,readMemberDirectory,type MemberCommand } from '@/lib/members/management';
import { journeys,journeyLabel,type MemberResult,type Stamp } from '@/lib/members/model';
import MemberEditor,{type EditorSpec} from './member-editor';
import MemberDetail from './member-detail';
import MemberConsole from './member-console';
import MemberDelete from './member-delete';
import {useMemberNotice} from '@/lib/members/use-notice';
import { UsersIcon } from '@/components/icons';
export default function MembersView(){
 const [stateFilter,setStateFilter]=useState('all'),[journeyFilter,setJourneyFilter]=useState('all'),[deleting,setDeleting]=useState<string|null|false>(false);
 const {notice,show:setNotice,clear:clearNotice}=useMemberNotice();
 const [detail,setDetail]=useState<MemberResult|null>(null),[detailError,setDetailError]=useState(''),[detailLoading,setDetailLoading]=useState(false);
 const client=useMemo(()=>createClient(),[]);
 const [view,setView]=useState<'families'|'athletes'>('families'),[search,setSearch]=useState(''),[offset,setOffset]=useState(0),[selection,setSelection]=useState<{familyId:string;athleteId:string|null}|null>(null);
 const [data,setData]=useState<MemberResult|null>(null),[restricted,setRestricted]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[editor,setEditor]=useState<EditorSpec|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{let cancelled=false;setLoading(true);setError('');const timer=setTimeout(()=>{void readMemberDirectory(client,search,offset,null,{state:stateFilter,journey:journeyFilter,view}).then(result=>{if(!cancelled){setData(result);setRestricted(result===null);setLoading(false)}}).catch(e=>{if(!cancelled){setError(e instanceof Error?e.message:'Members could not be loaded.');setLoading(false)}})},200);return ()=>{cancelled=true;clearTimeout(timer)}},[client,search,offset,retry,stateFilter,journeyFilter,view]);
 useEffect(()=>{if(!selection)return;let cancelled=false;setDetailLoading(true);setDetailError('');void readMemberDirectory(client,'',0,selection.familyId,{state:'all',journey:'all'}).then(result=>{if(!cancelled){setDetail(result);setDetailLoading(false)}}).catch(()=>{if(!cancelled){setDetailError('Family could not be loaded. Please retry.');setDetailLoading(false)}});return()=>{cancelled=true}},[client,selection?.familyId,retry]);
 const family=selection?detail?.families.find(f=>f.id===selection.familyId):null;
 const save=(command:MemberCommand,ack:boolean)=>manageMember(client,command,ack);
 function saved(id:string){setEditor(null);setSelection({familyId:id,athleteId:selection?.athleteId||null});setNotice('Member details saved.');setRetry(value=>value+1)}
 async function status(entity:'family'|'contact'|'athlete',record:Stamp){
  if(!family||busy)return;const next=record.status==='active'?'archived':'active';
  if(!confirm(`${next==='archived'?'Archive':'Reactivate'} this ${entity}? ${entity==='family'?'Connected contacts and athletes retain their own status.':entity==='contact'&&next==='archived'?'Primary and athlete contact links will be cleared; restore them through Edit contact after reactivation.':'This preserves the record and its history.'}`))return;
  setBusy(true);setError('');try{await manageMember(client,{action:'set_status',familyId:family.id,recordId:record.id,updatedAt:record.updated_at,data:{entity,status:next}});setNotice(`${journeyLabel(entity)} ${next==='active'?'reactivated':'archived'}.`);setRetry(value=>value+1)}catch(e){setError(e instanceof Error?e.message:'Could not change status.')}finally{setBusy(false)}
 }
 const athletes=data?.families.flatMap(f=>f.athletes.filter(a=>(journeyFilter==='all'||a.journey_status===journeyFilter)&&(stateFilter==='all'||a.status===stateFilter)).map(a=>({family:f,athlete:a})))||[];
 return <section className="membersFoundation" aria-labelledby="members-title"><header className="membersHeader"><div><span className="membersEyebrow">Your club community</span><h1 id="members-title">Members</h1><p>One family account, connected throughout every athlete’s journey.</p></div>{!restricted&&<button className="btn btnPrimary" disabled={loading||!data} onClick={()=>{setNotice('');setEditor({kind:'create'})}}><span aria-hidden="true">＋</span> Add member</button>}</header>
 {!selection&&notice&&<div role="status" className="notice success memberActions"><span>{notice}</span><button className="btn btnSecondary" onClick={clearNotice} aria-label="Dismiss success notification">Close</button></div>}
 <div className="membersCounts"><div><span>Families</span><strong>{data?.family_count??'—'}</strong></div><div><span>Athletes</span><strong>{data?.athlete_count??'—'}</strong></div></div>
 <nav className="membersTabs" aria-label="Member views">{(['families','athletes'] as const).map(item=><button key={item} aria-current={view===item?'page':undefined} className={view===item?'selected':''} onClick={()=>{clearNotice();setView(item);setSelection(null);setOffset(0)}}>{journeyLabel(item)}</button>)}</nav>
 {!restricted&&<div className="membersTools"><label htmlFor="members-search">Search families, contacts, email, mobile or athletes<input id="members-search" type="search" maxLength={100} value={search} onChange={e=>{setSearch(e.target.value);setOffset(0)}} placeholder="Search your club’s members"/></label><label>{view==='families'?'Family account':'Athlete record'}<select value={stateFilter} onChange={e=>{setStateFilter(e.target.value);setOffset(0)}}><option value="all">Active & archived</option><option value="active">Active</option><option value="archived">Archived</option></select></label><label>Athlete journey<select value={journeyFilter} onChange={e=>{setJourneyFilter(e.target.value);setOffset(0)}}><option value="all">All journeys</option>{journeys.map(j=><option key={j} value={j}>{journeyLabel(j)}</option>)}</select></label></div>}
 {error?<div className="card membersEmpty" role="alert"><h2>Members could not be loaded</h2><p>{error}</p><button className="btn btnSecondary" onClick={()=>setError('')}>Dismiss error</button><button className="btn btnSecondary" onClick={()=>setRetry(value=>value+1)}>Try again</button></div>:!data&&!restricted&&!loading?<div className="membersEmpty"><p>No member data loaded.</p><button className="btn btnSecondary" onClick={()=>setRetry(v=>v+1)}>Reload members</button></div>:loading&&!data?<p className="membersEmpty" role="status">Loading members…</p>:restricted?<div className="card membersEmpty"><UsersIcon/><h2>Member privacy comes first</h2><p>Platform Admin access does not include member personal data. Club Owners and Club Administrators manage their own club’s records.</p></div>:<div className="card membersContent">
 {(view==='families'?!data?.families.length:!athletes.length)?<div className="membersEmpty"><UsersIcon/><h2>{search||stateFilter!=='all'||journeyFilter!=='all'?'No matching members':view==='families'?'A home for every family':'Every athlete has a place'}</h2><p>{search||stateFilter!=='all'||journeyFilter!=='all'?'Try another search or adjust the filters.':'Add a family to start connecting athletes and their trusted contacts.'}</p></div>:<div className="membersRecords">{view==='families'?data?.families.map(f=>{const primary=f.contacts.find(c=>c.id===f.primary_contact_id);return <article key={f.id}><div><h2>{f.display_name}</h2><span className="membersStatus" data-status={f.status}>{journeyLabel(f.status)}</span><p>{primary?`Primary contact: ${primary.display_name}`:'No primary contact selected'}</p>{primary&&<p>{primary.email||'No email'} · {primary.phone||'No mobile number'}</p>}<ul>{f.athletes.map(a=><li key={a.id}>{a.display_name} · {journeyLabel(a.journey_status)}{a.status==='archived'?' · Archived':''}</li>)}</ul>{!f.athletes.length&&<p>No connected athletes yet.</p>}</div><button className="btn btnSecondary" onClick={()=>{clearNotice();setSelection({familyId:f.id,athleteId:null})}}>View family</button></article>}):athletes.map(({family:f,athlete:a})=><article key={a.id}><div><h2>{a.display_name}</h2><p>{f.display_name}</p><span className="membersStatus">{journeyLabel(a.journey_status)} · {journeyLabel(a.status)}</span></div><button className="btn btnSecondary" onClick={()=>{clearNotice();setSelection({familyId:f.id,athleteId:a.id})}}>View athlete</button></article>)}</div>}
 <div className="memberPagination"><span>{data?.matched_families||0} matching families · includes archived records{view==='athletes'?' · athletes grouped by family':''}</span><div className="memberActions"><button className="btn btnSecondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous</button><button className="btn btnSecondary" disabled={offset+25>=(data?.matched_families||0)} onClick={()=>setOffset(offset+25)}>Next</button></div></div>
 </div>}
 {selection&&<MemberConsole title={family?.display_name||'Family account'} reference={family?journeyLabel(family.status):''} onClose={()=>{clearNotice();setSelection(null)}}>{notice&&<div role="status" className="notice success memberActions"><span>{notice}</span><button className="btn btnSecondary" onClick={clearNotice}>Close</button></div>}{detailLoading?<p role="status">Loading family…</p>:detailError?<div className="notice danger" role="alert">{detailError}<button className="btn btnSecondary" onClick={()=>setRetry(v=>v+1)}>Retry</button></div>:family?<MemberDetail family={family} athleteId={selection.athleteId} onFamily={()=>{clearNotice();setSelection({...selection,athleteId:null})}} onAthlete={id=>{clearNotice();setSelection({...selection,athleteId:id})}} onEdit={setEditor} onStatus={(entity,record)=>void status(entity,record)} onBack={()=>{clearNotice();setSelection(null)}} busy={busy} onSaved={()=>{setNotice('Member details saved.');setRetry(v=>v+1)}} canDelete={detail?.can_delete===true} onDelete={setDeleting}/>:<p>Family unavailable.</p>}</MemberConsole>}
 {deleting!==false&&family&&<MemberDelete family={family} athlete={family.athletes.find(a=>a.id===deleting)} onClose={()=>setDeleting(false)} onDelete={async name=>{await deleteMember(client,family.id,deleting,name);setDeleting(false);setNotice(deleting?'Athlete permanently deleted.':'Family permanently deleted.');setSelection(deleting?{familyId:family.id,athleteId:null}:null);setRetry(v=>v+1)}}/>}
 {editor&&<MemberEditor spec={editor} onClose={()=>setEditor(null)} onSave={save} onSaved={saved}/>}
 </section>;
}
