"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import AvLogo from "@/components/av-logo";

type Club={id:string;name:string;slug:string;email:string|null;telephone:string|null;timezone:string;primary_colour:string;secondary_colour:string;active:boolean;created_at:string;last_activity:string|null;staff_count:number;owner:{full_name:string;contact_email:string|null;is_active:boolean}|null};
const empty={club:{name:"",slug:"",contact_email:"",telephone:"",timezone:"Europe/London",primary_colour:"#6D3A91",secondary_colour:"#243044",active:true},owner:{full_name:"",username:"",contact_email:"",password:""}};
export default function PlatformAdmin(){
 const[clubs,setClubs]=useState<Club[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[creating,setCreating]=useState(false),[step,setStep]=useState(1),[draft,setDraft]=useState(empty),[selected,setSelected]=useState<Club|null>(null),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);const r=await fetch("/api/platform-admin/clubs",{cache:"no-store"});if(r.ok)setClubs((await r.json()).clubs);else setMessage("Platform clubs could not be loaded.");setLoading(false)}
 useEffect(()=>{void load()},[]);
 const summary=useMemo(()=>({active:clubs.filter(c=>c.active).length,suspended:clubs.filter(c=>!c.active).length,users:clubs.reduce((n,c)=>n+c.staff_count,0),recent:clubs.filter(c=>Date.now()-new Date(c.created_at).getTime()<30*864e5).length}),[clubs]);
 function setClub(key:string,value:any){setDraft({...draft,club:{...draft.club,[key]:value}})}function setOwner(key:string,value:string){setDraft({...draft,owner:{...draft.owner,[key]:value}})}
 async function create(event:FormEvent){event.preventDefault();if(step<3){setStep(step+1);return}setBusy(true);setMessage("");try{const r=await fetch("/api/platform-admin/clubs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(draft)}),body=await r.json();if(!r.ok)throw new Error(body.error);setCreating(false);setStep(1);setDraft(empty);setMessage(`${body.club.name} was created securely.`);await load()}catch(e:any){setMessage(e.message||"Club creation failed.")}finally{setBusy(false)}}
 async function saveClub(next:Club){setBusy(true);setMessage("");try{const r=await fetch("/api/platform-admin/clubs",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:next.id,name:next.name,email:next.email,telephone:next.telephone,timezone:next.timezone,primary_colour:next.primary_colour,secondary_colour:next.secondary_colour,active:next.active})}),body=await r.json();if(!r.ok)throw new Error(body.error);setSelected(null);await load()}catch(e:any){setMessage(e.message||"Club update failed.")}finally{setBusy(false)}}
 return <main className="platformPage"><header className="platformHeader"><a href="/dashboard" aria-label="Back to workspace"><AvLogo size={46}/></a><div><span>AV Gymnastics Solutions</span><h1>Platform Admin</h1></div><a className="platformBack" href="/dashboard">Back to workspace</a></header><div className="platformBody">
  <div className="platformIntro"><div><p className="platformEyebrow">Customer management</p><h2>Clubs</h2><p>Manage independent club workspaces and their first owners.</p></div><button onClick={()=>setCreating(true)}>Create club</button></div>
  {message&&<div className="platformNotice">{message}</div>}
  <section className="platformStats"><article><span>Active clubs</span><strong>{summary.active}</strong></article><article><span>Suspended clubs</span><strong>{summary.suspended}</strong></article><article><span>Total users</span><strong>{summary.users}</strong></article><article><span>New in 30 days</span><strong>{summary.recent}</strong></article></section>
  <section className="platformPanel"><div className="platformTableHead"><span>Club</span><span>Status</span><span>Primary owner</span><span>Staff</span><span>Created</span><span/></div>{loading?<p className="platformEmpty">Loading clubs…</p>:clubs.map(c=><article className="platformClub" key={c.id}><div><strong>{c.name}</strong><small>{c.slug}</small></div><div><b className={c.active?"active":"suspended"}>{c.active?"Active":"Suspended"}</b></div><div><span>{c.owner?.full_name||"No owner"}</span><small>{c.owner?.contact_email||c.email||"No contact email"}</small></div><div><span>{c.staff_count}</span><small>staff</small></div><div><span>{new Date(c.created_at).toLocaleDateString("en-GB")}</span><small>Last activity {c.last_activity?new Date(c.last_activity).toLocaleDateString("en-GB"):"—"}</small></div><button onClick={()=>setSelected({...c})}>Manage</button></article>)}</section>
 </div>
 {creating&&<div className="platformModal"><form onSubmit={create}><header><div><span>Step {step} of 3</span><h2>{step===1?"Club details":step===2?"First Club Owner":"Review onboarding"}</h2></div><button type="button" onClick={()=>setCreating(false)}>×</button></header><div className="platformForm">{step===1&&<><label>Club name<input required value={draft.club.name} onChange={e=>setClub("name",e.target.value)}/></label><label>Unique slug<input required pattern="[a-z0-9][a-z0-9-]+[a-z0-9]" value={draft.club.slug} onChange={e=>setClub("slug",e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,""))}/></label><label>Contact email<input required type="email" value={draft.club.contact_email} onChange={e=>setClub("contact_email",e.target.value)}/></label><label>Contact phone<input value={draft.club.telephone} onChange={e=>setClub("telephone",e.target.value)}/></label><label>Timezone<input required value={draft.club.timezone} onChange={e=>setClub("timezone",e.target.value)}/></label><div className="platformColours"><label>Primary colour<input type="color" value={draft.club.primary_colour} onChange={e=>setClub("primary_colour",e.target.value)}/></label><label>Secondary colour<input type="color" value={draft.club.secondary_colour} onChange={e=>setClub("secondary_colour",e.target.value)}/></label></div></>}{step===2&&<><label>Full name<input required value={draft.owner.full_name} onChange={e=>setOwner("full_name",e.target.value)}/></label><label>Username<input required value={draft.owner.username} onChange={e=>setOwner("username",e.target.value.toLowerCase().replace(/\s/g,""))}/></label><label>Recovery email<input required type="email" value={draft.owner.contact_email} onChange={e=>setOwner("contact_email",e.target.value)}/></label><label>Initial password<input required minLength={8} type="password" autoComplete="new-password" value={draft.owner.password} onChange={e=>setOwner("password",e.target.value)}/></label><div className="platformFixedRole"><span>Role</span><strong>Club Owner</strong></div></>}{step===3&&<div className="platformReview"><div><span>Club</span><strong>{draft.club.name}</strong><small>{draft.club.slug} · {draft.club.contact_email}</small></div><div><span>First owner</span><strong>{draft.owner.full_name}</strong><small>@{draft.owner.username} · Club Owner</small></div><div><span>Security assignment</span><strong>New isolated club tenant</strong><small>The server assigns the new club UUID to Auth metadata and the owner profile.</small></div></div>}</div><footer>{step>1&&<button type="button" onClick={()=>setStep(step-1)}>Back</button>}<button disabled={busy}>{busy?"Creating securely…":step===3?"Create club & owner":"Continue"}</button></footer></form></div>}
 {selected&&<div className="platformModal"><form onSubmit={e=>{e.preventDefault();void saveClub(selected)}}><header><div><span>Club details</span><h2>{selected.name}</h2></div><button type="button" onClick={()=>setSelected(null)}>×</button></header><div className="platformForm"><label>Club name<input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label>Contact email<input type="email" value={selected.email||""} onChange={e=>setSelected({...selected,email:e.target.value})}/></label><label>Contact phone<input value={selected.telephone||""} onChange={e=>setSelected({...selected,telephone:e.target.value})}/></label><label>Timezone<input value={selected.timezone} onChange={e=>setSelected({...selected,timezone:e.target.value})}/></label><div className="platformFixedRole"><span>Status</span><strong>{selected.active?"Active":"Suspended"}</strong><button type="button" className={selected.active?"danger":""} onClick={()=>setSelected({...selected,active:!selected.active})}>{selected.active?"Suspend club":"Reactivate club"}</button></div></div><footer><button type="button" onClick={()=>setSelected(null)}>Cancel</button><button disabled={busy}>Save changes</button></footer></form></div>}
 </main>
}
