'use client';
import './enrolments.css';
import {useEffect,useMemo,useRef,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {enrolmentCommand,loadEnrolmentContext} from '@/lib/enrolments/data';
import {availableFor,enrolmentError,enrolmentStatusLabel,weekdayLabel,type Enrolment,type EnrolmentContext,type EnrolmentDraft,type EnrolmentStatus} from '@/lib/enrolments/model';

type Props={profileId?:string;athlete?:{id:string;display_name:string};canManage?:boolean};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const emptyDraft=(profileId='',athleteId=''):EnrolmentDraft=>({athlete_id:athleteId,class_profile_id:profileId,status:'waiting',start_date:today(),end_date:'',source:'',internal_notes:'',session_ids:[],change_from:today(),override_reason:''});

export function EnrolmentForm({context,profileId,athleteId,record,search,onSearch,onCancel,onSaved}:{context:EnrolmentContext;profileId?:string;athleteId?:string;record?:Enrolment;search:string;onSearch:(value:string)=>void;onCancel:()=>void;onSaved:()=>void}){
 const client=useMemo(()=>createClient(),[]),flight=useRef(false),request=useRef<string|null>(null);
 const [draft,setDraft]=useState<EnrolmentDraft>(()=>record?{athlete_id:record.athlete_id,class_profile_id:record.class_profile_id,status:record.status,start_date:record.start_date,end_date:record.end_date||'',source:record.source,internal_notes:record.internal_notes,session_ids:record.sessions.filter(s=>!s.superseded_at&&(!s.selected_to||s.selected_to>=today())).map(s=>s.class_id),change_from:today(),override_reason:''}:emptyDraft(profileId,athleteId));
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[override,setOverride]=useState(false);
 const sessions=context.sessions.filter(session=>session.class_profile_id===draft.class_profile_id&&session.active);
 const profile=context.profiles.find(item=>item.id===draft.class_profile_id);
 const capacityIssues=(draft.status==='active'||draft.status==='trial')?sessions.filter(session=>draft.session_ids.includes(session.id)&&availableFor(session,draft.start_date,draft.end_date||null,record?.id)<=0):[];
 async function save(){
  const invalid=enrolmentError(draft,sessions,Boolean(record));if(invalid){setError(invalid);return}
  if(capacityIssues.length&&(!override||!draft.override_reason.trim())){setError('Capacity is full. Confirm the override and record a reason, or use Waiting list.');return}
  if(flight.current)return;flight.current=true;setBusy(true);setError('');request.current??=crypto.randomUUID();
  try{await enrolmentCommand(client,record?'edit':'create',record?.id||null,{athlete_id:draft.athlete_id,class_profile_id:draft.class_profile_id,status:draft.status,start_date:draft.start_date,end_date:draft.end_date||null,source:draft.source.trim(),internal_notes:draft.internal_notes.trim(),session_ids:draft.session_ids,change_from:draft.change_from,override_reason:override?draft.override_reason.trim():null},request.current);onSaved()}
  catch(e){setError(e instanceof Error?e.message:'The enrolment could not be saved.');request.current=null}
  finally{flight.current=false;setBusy(false)}
 }
 const chooseSession=(id:string)=>setDraft(value=>({...value,session_ids:value.session_ids.includes(id)?value.session_ids.filter(item=>item!==id):[...value.session_ids,id]}));
 return <section className="enrolmentEditor" aria-label={record?'Edit enrolment':'New enrolment'}>
  <header><div><span>{record?'Update enrolment':'Add athlete'}</span><h3>{record?`${record.athlete_name} · ${record.class_name}`:'Enrol in weekly class'}</h3></div><button className="btn btnSecondary" type="button" disabled={busy} onClick={onCancel}>Cancel</button></header>
  {error&&<p className="enrolmentError" role="alert">{error}</p>}
  {!athleteId&&!record&&<div className="enrolmentPicker"><label>Find athlete<input type="search" value={search} onChange={event=>onSearch(event.target.value)} placeholder="Search athlete or family"/></label><div>{context.athletes.map(item=><button type="button" className={draft.athlete_id===item.id?'selected':''} key={item.id} onClick={()=>setDraft(value=>({...value,athlete_id:item.id}))}><strong>{item.display_name}</strong><span>{item.family_name}</span></button>)}</div></div>}
  {!profileId&&!record&&<div className="enrolmentPicker"><label>Find class<input type="search" value={search} onChange={event=>onSearch(event.target.value)} placeholder="Search active classes"/></label><div>{context.profiles.map(item=><button type="button" className={draft.class_profile_id===item.id?'selected':''} key={item.id} onClick={()=>setDraft(value=>({...value,class_profile_id:item.id,session_ids:[]}))}><strong>{item.name}</strong><span>Capacity {item.capacity}</span></button>)}</div></div>}
  <div className="enrolmentFields"><label>{record?'Current status':'Status'}<select disabled={Boolean(record)} value={draft.status} onChange={event=>setDraft(value=>({...value,status:event.target.value as EnrolmentStatus}))}>{(['enquiry','waiting','trial','active','paused'] as const).map(status=><option key={status} value={status}>{enrolmentStatusLabel(status)}</option>)}</select></label><label>Inclusive start date<input type="date" value={draft.start_date} onChange={event=>setDraft(value=>({...value,start_date:event.target.value}))}/></label><label>Optional end date<input type="date" min={draft.start_date} value={draft.end_date} onChange={event=>setDraft(value=>({...value,end_date:event.target.value}))}/></label>{record&&<label>Session changes take effect<input type="date" min={today()} value={draft.change_from} onChange={event=>setDraft(value=>({...value,change_from:event.target.value}))}/></label>}<label>Source<input maxLength={120} value={draft.source} onChange={event=>setDraft(value=>({...value,source:event.target.value}))} placeholder="e.g. Website enquiry"/></label><label className="enrolmentNotes">Internal notes<textarea maxLength={4000} value={draft.internal_notes} onChange={event=>setDraft(value=>({...value,internal_notes:event.target.value}))}/></label></div>
  <fieldset className="enrolmentSessions"><legend>Weekly sessions attended</legend>{profile?<p>{profile.name} · select one or more active recurrences</p>:<p>Select a class to see its weekly sessions.</p>}{sessions.map(session=>{const available=availableFor(session,draft.start_date,draft.end_date||null,record?.id);return <label className={draft.session_ids.includes(session.id)?'selected':''} key={session.id}><input type="checkbox" checked={draft.session_ids.includes(session.id)} onChange={()=>chooseSession(session.id)}/><span><strong>{weekdayLabel(session.weekday)} · {session.start_time.slice(0,5)}–{session.finish_time.slice(0,5)}</strong><small>{session.venue_name} · Capacity {session.capacity} · <b className={available<=0?'full':''}>{Math.max(0,available)} available</b></small></span></label>})}</fieldset>
  {capacityIssues.length>0&&<div className="enrolmentOverride"><label><input type="checkbox" checked={override} onChange={event=>setOverride(event.target.checked)}/> Explicitly override capacity</label>{override&&<label>Required override reason<textarea value={draft.override_reason} maxLength={500} onChange={event=>setDraft(value=>({...value,override_reason:event.target.value}))}/></label>}</div>}
  <footer><button className="btn btnPrimary" type="button" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':record?'Save enrolment':'Create enrolment'}</button></footer>
 </section>;
}

export default function EnrolmentsPanel({profileId,athlete,canManage=true}:Props){
 const client=useMemo(()=>createClient(),[]),[context,setContext]=useState<EnrolmentContext|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[editing,setEditing]=useState<Enrolment|null|'new'>(null),[transition,setTransition]=useState<{record:Enrolment;status:EnrolmentStatus;reason:string;override_reason:string;final_date:string}|null>(null),[revision,setRevision]=useState(0),flight=useRef(false);
 useEffect(()=>{let cancelled=false;setLoading(true);const timer=setTimeout(()=>{void loadEnrolmentContext(client,profileId||null,athlete?.id||null,search).then(value=>{if(!cancelled){setContext(value);setError('')}}).catch(e=>{if(!cancelled)setError(e instanceof Error?e.message:'Enrolments could not be loaded.')}).finally(()=>{if(!cancelled)setLoading(false)})},search?220:0);return()=>{cancelled=true;clearTimeout(timer)}},[client,profileId,athlete?.id,search,revision]);
 async function saveTransition(){
  if(!transition||flight.current)return;const ending=transition.status==='ended';
  if(!transition.reason.trim()){setError('Record a reason for this status change.');return}
  const selected=new Set(transition.record.sessions.filter(item=>!item.superseded_at).map(item=>item.class_id));
  const full=(transition.status==='active'||transition.status==='trial')?context!.sessions.filter(session=>selected.has(session.id)&&availableFor(session,transition.record.start_date,transition.record.end_date,transition.record.id)<=0):[];
  if(full.length&&!transition.override_reason.trim()){setError('Capacity is full. Record an explicit override reason to continue.');return}
  flight.current=true;setError('');try{await enrolmentCommand(client,ending?'end':'status',transition.record.id,ending?{final_date:transition.final_date,reason:transition.reason.trim()}:{status:transition.status,reason:transition.reason.trim(),override_reason:transition.override_reason.trim()||null},crypto.randomUUID());setTransition(null);setRevision(value=>value+1)}catch(e){setError(e instanceof Error?e.message:'Status could not be changed.')}finally{flight.current=false}
 }
 if(loading&&!context)return <p role="status">Loading enrolments…</p>;
 if(error&&!context)return <div className="enrolmentError" role="alert">{error}<button className="btn btnSecondary" onClick={()=>setRevision(value=>value+1)}>Retry</button></div>;
 if(!context)return null;
 if(editing)return <EnrolmentForm context={context} profileId={profileId} athleteId={athlete?.id} record={editing==='new'?undefined:editing} search={search} onSearch={setSearch} onCancel={()=>{setEditing(null);setSearch('')}} onSaved={()=>{setEditing(null);setSearch('');setRevision(value=>value+1)}}/>;
 if(transition){const selected=new Set(transition.record.sessions.filter(item=>!item.superseded_at).map(item=>item.class_id));const full=(transition.status==='active'||transition.status==='trial')?context.sessions.filter(session=>selected.has(session.id)&&availableFor(session,transition.record.start_date,transition.record.end_date,transition.record.id)<=0):[];return <section className="enrolmentTransition"><header><div><span>Confirm status change</span><h3>{transition.record.athlete_name} · {enrolmentStatusLabel(transition.record.status)} → {enrolmentStatusLabel(transition.status)}</h3></div></header><p>This keeps the dated status history and all previous weekly-session selections.</p>{transition.status==='ended'&&<label>Inclusive final date<input type="date" min={transition.record.start_date} max={context.today} value={transition.final_date} onChange={event=>setTransition({...transition,final_date:event.target.value})}/></label>}<label>Reason<textarea maxLength={500} value={transition.reason} onChange={event=>setTransition({...transition,reason:event.target.value})}/></label>{full.length>0&&<label className="enrolmentOverride">Capacity override reason<textarea maxLength={500} value={transition.override_reason} onChange={event=>setTransition({...transition,override_reason:event.target.value})}/></label>}{error&&<p className="enrolmentError" role="alert">{error}</p>}<footer><button className="btn btnSecondary" onClick={()=>{setTransition(null);setError('')}}>Cancel</button><button className="btn btnPrimary" onClick={()=>void saveTransition()}>Confirm {enrolmentStatusLabel(transition.status)}</button></footer></section>}
 const rows=context.enrolments;
 return <div className="enrolmentsPanel">
  {error&&<p className="enrolmentError" role="alert">{error}</p>}
  {profileId&&<div className="enrolmentCounts"><div><span>Active</span><strong>{context.counts.active}</strong></div><div><span>Trial</span><strong>{context.counts.trial}</strong></div><div><span>Waiting list</span><strong>{context.counts.waiting}</strong></div></div>}
  <div className="enrolmentPanelHead"><div><h3>{profileId?'Class roster':'Class enrolments'}</h3><p>{profileId?'Athletes connected to this shared class profile.':'Weekly classes connected to this athlete.'}</p></div>{canManage&&<button className="btn btnPrimary" type="button" onClick={()=>setEditing('new')}>{profileId?'Add athlete':'Enrol in class'}</button>}</div>
  <div className="enrolmentRows">{rows.map(record=><article key={record.id}><header><div><h4>{profileId?record.athlete_name:record.class_name}</h4><p>{profileId?record.family_name:record.athlete_name} · {record.start_date}{record.end_date?` to ${record.end_date}`:' onwards'}</p></div><span className={`enrolmentStatus status-${record.status}`}>{enrolmentStatusLabel(record.status)}</span></header><div className="enrolmentSessionSummary">{record.sessions.filter(session=>!session.superseded_at).map(session=><span key={session.id}>{weekdayLabel(session.weekday)} {session.start_time.slice(0,5)} · {session.venue_name}</span>)}</div>{record.source&&<p>Source: {record.source}</p>}<div className="enrolmentActions">{canManage&&record.status!=='ended'&&<><button className="btn btnSecondary" onClick={()=>setEditing(record)}>Edit sessions & dates</button>{(['waiting','trial','active','paused','ended'] as EnrolmentStatus[]).filter(status=>status!==record.status).map(status=><button className={status==='ended'?'btn btnDanger':'btn btnSecondary'} key={status} onClick={()=>setTransition({record,status,reason:'',override_reason:'',final_date:context.today})}>{status==='ended'?'End enrolment':`Move to ${enrolmentStatusLabel(status)}`}</button>)}</>}</div><details><summary>Status history</summary>{record.history.map(item=><p key={item.id}><strong>{enrolmentStatusLabel(item.to_status)}</strong> · {item.effective_date}<br/><span>{item.reason}</span></p>)}</details></article>)}{!rows.length&&<div className="enrolmentEmpty">No enrolments yet.</div>}</div>
 </div>;
}
